var g=void 0,h=!0,j=null,l=!1;function aa(a){return function(){return a}}"undefined"==typeof preInitFuncs&&(preInitFuncs=[]);preInitFuncs.push(function(){"console"==viewMode&&"undefined"==typeof inEditorPreview&&(document?window.onload=function(a){a=document.createElement("textarea");a.style.width="100%";a.style.height="480px";a.id="GLBCONSOLE";document.body.appendChild(a);ba()}:ba())});var ca=(new Date).getTime();function da(){}da.prototype.toString=aa("GLB Exit");
var ea=0,ha=l,p=-1,s=Array(64),ia=l;
function ja(){switch(""){case "":return"HTML5";case "DOCUMENTS":case "APPDATA":case "TEMP":return"/";case "ID":return""+uniqueId;case "DEVICE":return"DESKTOP";case "BATTERY":var a=navigator.w||window.navigator.w||navigator.w||navigator.R||navigator.Z;return a?100*a.Q:100;case "TIME":var a=new Date,b=function(a){a=ka(a);1==a.length&&(a="0"+a);return a};return b(a.getFullYear())+"-"+b(a.getMonth())+"-"+b(a.getDate())+" "+b(a.getHours())+":"+b(a.getMinutes())+":"+b(a.getSeconds());case "COMPILED":return rot13(compileTime);
case "VERSION":return rot13(userDefVersion);case "HOSTID":return rot13(hostId);case "LOCALE":return navigator.language||window.navigator.Y||window.navigator.language;default:return""}}function la(){eval("if (window['GLB_ON_QUIT']) window.GLB_ON_QUIT(); else ret = 0;")}var na=[];function t(a){throw a;}
function oa(a){a=a.message?a.message:a.toString();0==a.indexOf("GLBERR")&&(a=a.substring(6));if(pa){for(var b=__debugInfo,a="Error:\n '"+a+"' "+("\nAppeared in line '"+qa(b,0,ra(b))+"' in file '"+qa(b,ra(b)+1)+"' "),b="",c=na.length-1;0<=c;c--)b+="\tin '"+na[c].name+"' in file '"+qa(na[c].info,ra(na[c].info)+1)+"' in line '"+qa(na[c].info,0,ra(na[c].info))+"'\n";a+="\n\n"+b}return a}function u(a,b,c){return 0<c?a<=b:0>c?a>=b:h}function v(a){return a instanceof Array?a[0]:a}
function w(a){switch(typeof a){case "undefined":case "function":case "string":case "boolean":case "number":break;default:return a instanceof Array?[w(a[0])]:a.z()}return a}function ba(){try{(ia||(main(),ia=h),!ea&&!ha)?(ha=h,"function"==typeof GLB_ON_INIT&&GLB_ON_INIT()):window.D(ba,100)}catch(a){a instanceof da&&alert(oa(a))}}
function x(a){if(a instanceof Array)return[x(a[0])];switch(typeof a){case "function":return 1;case "undefined":t("Cannot cast 'undefined'");case "number":return~~a;case "string":return isNaN(a)||""==a?0:parseInt(a,10);case "boolean":return a?1:0;case "object":return x(a.toString());default:t("Unknown type!")}}
function ka(a){if(a instanceof Array)return[ka(a[0])];switch(typeof a){case "function":return"1";case "undefined":t("Cannot cast undefined to string");case "boolean":return a?"1":"0";case "number":return""+a;case "string":return a;case "object":return a.toString();default:t("Unknown type")}}
window.localStorage||Object.defineProperty(window,"localStorage",new function(){var a=[],b={};Object.defineProperty(b,"getItem",{value:function(a){return a?this[a]:j},writable:l,configurable:l,enumerable:l});Object.defineProperty(b,"key",{value:function(b){return a[b]},writable:l,configurable:l,enumerable:l});Object.defineProperty(b,"setItem",{value:function(a,b){a&&(document.cookie=escape(a)+"="+escape(b)+"; path=/")},writable:l,configurable:l,enumerable:l});Object.defineProperty(b,"length",{get:function(){return a.length},
configurable:l,enumerable:l});Object.defineProperty(b,"removeItem",{value:function(a){if(a){var b=new Date;b.setDate(b.getDate()-1);document.cookie=escape(a)+"=; expires="+b.toGMTString()+"; path=/"}},writable:l,configurable:l,enumerable:l});this.get=function(){var c,e;for(e in b)c=a.indexOf(e),-1===c?b.setItem(e,b[e]):a.splice(c,1),delete b[e];for(;0<a.length;a.splice(0,1))b.removeItem(a[0]);for(var f=0,k=document.cookie.split(/\s*;\s*/);f<k.length;f++)c=k[f].split(/\s*=\s*/),1<c.length&&(b[e=unescape(c[0])]=
unescape(c[1]),a.push(e));return b};this.configurable=l;this.enumerable=h});window.D=window.W||window.$||window.S||window.U||window.T||function(a){window.setTimeout(a,1E3/60)};window.onbeforeunload=function(){la();localStorage&&localStorage.setItem("filesystem",sa.save())};function ta(){this.a=[];this.c=[0];this.m=0;return this}
ta.prototype.z=function(){var a=new ta;a.c=this.c.slice(0);a.m=this.m;switch(typeof this.m){case "number":case "string":case "boolean":case "function":a.a=this.a.slice(0);break;default:if(this.a!=g&&this.a.c!=g)for(var b=0;b<this.a.length;b++)a.a[b]=w(this.a[b]);else a.a=[]}return a};
ta.prototype.b=function(){p=0;for(var a=arguments.length-1;0<=a;a--){a>=this.c.length&&t("Wrong dimension count '"+(arguments.length-1)+"' expected '"+this.c.length+"'");var b=arguments[a];0>b&&(b=this.c[a]+b);if(0>b||b>=this.c[a]){for(var c="",e=l,f=0;f<arguments.length;f++)e&&(c+=", "),c+="'"+arguments[f]+"'",e=h;t("Array index out of bounds access, position: "+("["+c+"]"))}s[a]=b}switch(arguments.length){case 1:p=s[0];break;case 2:p=s[0]+s[1]*this.c[0];break;case 3:p=s[0]+s[1]*this.c[0]+s[2]*this.c[0]*
this.c[1];break;case 4:p=s[0]+s[1]*this.c[0]+s[2]*this.c[0]*this.c[1]+s[3]*this.c[0]*this.c[1]*this.c[2];break;default:b=this.a.length/this.c[arguments.length-1];for(a=arguments.length-1;0<=a;a--)p+=s[a]*b,b/=this.c[a-1]}return this};function ua(a,b){var c=Array,e=1;for(d in b)b[d]=x(b[d]),e*=b[d];a.a=c(e);a.c=b;for(c=a.m=0;c<a.a.length;c++)a.a[c]=w(0)}function va(a){if(0==a)return 0;0>a&&(a=-a);wa=(9301*wa+49297)%233280;return(a+1)*(wa/233280)}function xa(a,b){return a>b?a:b}var wa=(new Date).getTime();
function qa(a,b,c){try{return-1==c?a.substr(b):a.substr(b,c)}catch(e){t("string error (MID$): '"+a+"' start: '"+b+"' count: '"+c+"'")}}function ra(a){return a.indexOf(":",g)}function ya(a){for(var b=0;;){b=a.indexOf("t.",b);if(-1==b)break;a=a.substring(0,b)+"window.filesystem."+a.substring(b+2);b+=18}return a}function za(a){for(i=0;i<a.length;i++)if(-1==" ".indexOf(a.charAt(i)))return a.substr(i);return""}
function Aa(a){for(i=a.length-1;0<=i;i--)if(-1==" ".indexOf(a.charAt(i)))return a.substr(0,i+1);return""}function Ba(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){}t("XMLHttpRequest not supported");return j}function Ga(a){var b=Ba();"/"==a.charAt(0)&&(a=a.substring(1));b.open("get",a,l);b.X="text";b.send(j);return b.responseText}var sa=new Ha(localStorage?localStorage.getItem("filesystem"):""),Ia=new Ha,Ja=Ga("DIR_STRUCTURE");
if(Ja==j)t("Cannot load dir structure!");else for(var Ka=Ja.split("\n"),La=0;La<Ka.length;La++){var Ma=Ka[La];if(-1!=Ma.indexOf(":")){var Na=Ma.substring(0,Ma.indexOf(":")),z=Ma.substring(Ma.indexOf(":")+1);switch(Na){case "var":if(-1!=z.indexOf("=")){var Oa=z.substring(0,z.indexOf("=")),Pa=z.substring(z.indexOf("=")+1);"undefined"==typeof isInWebWorker?window[Oa]=Pa:eval(Oa+" = '"+Pa+"'")}else t("Expecting '='");break;case "folder":sa.i(z);Ia.i(z);break;case "static":Ia.j(z,[]);break;case "editable":Ia.j(z,
function(a){var b=Ga(a.path+".GLBSCRIPT_DATA");a.data=b.split(",");return a.data});break;default:t("Unknown command '"+Na+"'")}}}
function Qa(a,b){for(var a=(za(Aa(b.A.J))+za(Aa(a))).toLowerCase(),c=0,e=b,f=0;f<a.length;f++)switch(a.charAt(f)){case "/":0<f?(e=e.K(a.substr(c,f-c)),c=f+1):c=1;break;case ".":var k=function(){f++;return f<a.length};if(!k())break;if("."==a.charAt(f)){e=e.getParent();if(!k())break;"/"!=a.charAt(f)&&t("Expecting '/'");c=f+1}else"/"==a.charAt(f)&&(c=f+1)}return new Ra(a.substr(c,a.length-c),e)}function Ra(a,b){this.name=a;this.dir=b}
function Ha(a){this.f=new Sa("",j,this);this.J="";this.getFile=function(a){a=Qa(a,this.f);return a.dir.getFile(a.name)};this.B=function(a){return Qa(a,this.f).dir};this.p=function(a){try{var c=Qa(a,this.f);return c.dir.p(c.name)}catch(e){}return l};this.o=function(a){try{var c=Qa(a,this.f);return c.dir.o(c.name)}catch(e){}return l};this.C=function(a){a=Qa(a,this.f);a.dir.C(a.name)};this.j=function(a,c){if(this.p(a)){var e=this.getFile(a);e.data=c;return e}e=Qa(a,this.f);return e.dir.j(a,e.name,c)};
this.cD=this.i=function(a){if(this.o(a))return this.B(a);a=Qa(a,this.f);return a.dir.i(a.name)};this.cF=this.j;this.save=function(){return this.f.save()};a!=g&&(window.filesystem=this,eval(ya(a)))}
function Sa(a,b,c){this.name=a;this.parent=b;this.e=[];this.files=[];this.A=c;this.o=function(a){for(var b=0;b<this.e.length;b++)if(this.e[b].name==a)return h;return l};this.p=function(a){for(var b=0;b<this.files.length;b++)if(this.files[b].name==a)return h;return l};this.C=function(a){for(var b=0;b<this.files.length;b++)if(this.files[b].name==a){this.files.splice(b,1);return}t("FileNotFound "+a)};this.i=function(a){a=new Sa(a,this,this.A);this.e.push(a);return a};this.j=function(a,b,c){a=new Ta(this,
b,c,a);this.files.push(a);return a};this.getFile=function(a){for(var b=0;b<this.files.length;b++)if(this.files[b].name==a)return this.files[b];t("file not found")};this.B=function(a){for(var b=0;b<this.e.length;b++)if(this.e[b].name==a)return this.e[b];t("Dir not found")};this.K=function(a){for(var b=0;b<this.e.length;b++)if(this.e[b].name==a)return this.e[b];t("Dir not found: "+a)};this.getParent=function(){return this.parent};this.q=function(){return(this.getParent()?this.getParent().q()+"/":"")+
this.name};this.save=function(){var a="";this.getParent()!=j&&(a='t.cD("'+this.q()+'");\n');for(var b=0;b<this.files.length;b++)a+=this.files[b].save();for(b=0;b<this.e.length;b++)a+=this.e[b].save();return a}}
function Ta(a,b,c,e){this.name=b;this.data=c;this.dir=a;this.path=e;this.getName=function(){return this.name};this.getData=function(){return"function"==typeof this.data?this.data(this):this.data};this.save=function(){return't.cF("'+this.dir.q()+"/"+this.name+'", '+JSON.stringify(this.getData())+");\n"}}"undefined"==typeof preInitFuncs&&(preInitFuncs=[]);
preInitFuncs.push(function(){if("2d"==viewMode||"undefined"!=typeof inEditorPreview)"undefined"==typeof window&&(window={}),window.onload=function(){"undefined"==typeof GFX_WIDTH&&(window.GFX_WIDTH=640);"undefined"==typeof GFX_HEIGHT&&(window.GFX_HEIGHT=480);var a=document.createElement("canvas");a.width=GFX_WIDTH;a.height=GFX_HEIGHT;a.id="GLBCANVAS";document.body.appendChild(a);Ua()}});
var Va=[],Wa=[],ea=0,Xa=j,A=j,B=j,Ya=C(0,0,0),Za=j,$a=l,ab=-1,bb=0,cb=0,db=j,eb=j,fb=[],gb=l,hb=j,ib=j,jb=l,kb=l,lb,mb,E=[],nb=document?"createTouch"in document:l;
function ob(){ea?GLB_ON_LOADING&&GLB_ON_LOADING():eb();if(pb){pb||t("ENDPOLY has to be in STARTPOLY - ENDPOLY ");if(0<F.length){if(4==F.length){pb||t("POLYNEWSTRIP has to be in STARTPOLY - ENDPOLY ");t("Invalid drawing mode!");var a=qb(g),b;b=F[0].d!=rb&&F[1].d!=rb&&F[2].d!=rb&&F[2].d!=rb?h:l;for(var c=A.globalAlpha,e=A.globalCompositeOperation,f=F,k=0;k<g.length;k++){var m=g[k],n=f[m[0]].x,y=f[m[1]].x,r=f[m[2]].x,q=f[m[0]].y,G=f[m[1]].y,H=f[m[2]].y,I=f[m[0]].H,J=f[m[1]].H,K=f[m[2]].H,L=f[m[0]].I,
M=f[m[1]].I,m=f[m[2]].I;A.save();A.beginPath();A.moveTo(n,q);A.lineTo(y,G);A.lineTo(r,H);A.closePath();A.clip();var fa=I*M+L*K+J*m-M*K-L*J-I*m;A.transform((n*M+L*r+y*m-M*r-L*y-n*m)/fa,(q*M+L*H+G*m-M*H-L*G-q*m)/fa,(I*y+n*K+J*r-y*K-n*J-I*r)/fa,(I*G+q*K+J*H-G*K-q*J-I*H)/fa,(I*M*r+L*y*K+n*J*m-n*M*K-L*J*r-I*y*m)/fa,(I*M*H+L*G*K+q*J*m-q*M*K-L*J*H-I*G*m)/fa);if(b){if(f[0].d==f[1].d&&f[1].d==f[2].d&&2<polyStacj.length&&f[2].d==f[3].d){if(!a.g)try{var n=a,Ca=a.L,Da=Ca.width,Ea=Ca.height,y=[],X=document.createElement("canvas");
X.width=Da;X.height=Ea;var ga=X.getContext("2d");ga.drawImage(Ca,0,0);for(var ma=ga.getImageData(0,0,Da,Ea).data,r=0;4>r;r++){X=document.createElement("canvas");X.width=Da;X.height=Ea;ga=X.getContext("2d");ga.drawImage(Ca,0,0);for(var xb=ga.getImageData(0,0,Da,Ea),Fa=xb.data,q=0,Rb=ma.length;q<Rb;q+=4)Fa[q]=0===r?ma[q]:0,Fa[q+1]=1===r?ma[q+1]:0,Fa[q+2]=2===r?ma[q+2]:0,Fa[q+3]=ma[q+3];ga.putImageData(xb,0,0);var yb=new Image;yb.src=X.toDataURL();y.push(yb)}n.g=y}catch(Sb){if(n=Sb,n instanceof DOMException)18==
n.code?t("Cannot access to ressource (maybe pixel data?). If you use Chrome, please run in localhost or use another browser!"):t("Unknown DOM error :(");else throw n;}if(a.g&&(n=(f[k].d&16711680)/65536,y=(f[k].d&65280)/256,r=f[k].d&255,A.globalAlpha=1,A.globalCompositeOperation="copy",A.drawImage(a.g[3],0,0),A.globalCompositeOperation="lighter",0<n&&(A.globalAlpha=n/255,A.drawImage(a.g[0],0,0)),0<y&&(A.globalAlpha=y/255,A.drawImage(a.g[1],0,0)),0<r))A.globalAlpha=r/255,A.drawImage(a.g[2],0,0)}}else A.drawImage(a.L,
0,0);A.restore()}b&&(A.globalAlpha=c,A.globalCompositeOperation=e);F.length=0}else t("Missing ENDPOLY function.");F.length=0}pb=l}sb&&(A.restore(),sb=l)}function tb(){try{if($a){hb&&(hb(),hb=j);ub();if(gb){if(kb||jb||lb||mb)gb=l}else if(-1==ab)ob();else{var a=(new Date).getTime()-ca,b=a-bb;b>=cb&&(ob(),cb=ab,b>cb&&(cb-=b-cb),bb=a)}jb=l}else $a=h,main();window.D(tb,frontbuffer.canvas)}catch(c){c instanceof da||alert(oa(c))}}
function vb(a){var b=eval("window['"+a+"']");b==g&&(eb=function(){t("Call to undefined loop!")},t("Cannot push undefined loop: '"+a+"'"));eb=b;fb.push([b,a])}function wb(){$a&&(zb(-2),Ab(Ya),zb(-1),frontbuffer.l.drawImage(Za.canvas,0,0),Ab(Ya),db&&Za.l.drawImage(db,0,0))}
function Ua(){function a(a){a.stopPropagation?(a.stopPropagation(),a.preventDefault()):(a.cancelBubble=h,a.returnValue=l)}var b=document.createElement("audio"),c=l,e=l;b.canPlayType&&(c=!!b.canPlayType&&""!=b.canPlayType("audio/mpeg"),c="maybe"==c||"probably"==c||c==h?h:l,e=!!b.canPlayType&&""!=b.canPlayType('audio/ogg; codecs="vorbis"'),e="maybe"==e||"probably"==e||e==h?h:l);!e&&!c&&console.log("No sound playback possible!");usedSoundFormat=e?"ogg":"mp3";frontbuffer=new Bb(document.getElementById("GLBCANVAS"),
-2);Cb(frontbuffer);b=document.createElement("canvas");b.width=frontbuffer.canvas.width;b.height=frontbuffer.canvas.height;Za=new Bb(b,-1);Cb(Za);"undefined"==typeof GLB_ON_LOADING&&(GLB_ON_LOADING=j);zb(-2);if(!A)throw t("Canvas unsupported, please use a newer browser."),window.onbeforeunload(),new da;B.oncontextmenu=aa(l);E.push(new Touch);nb?(B.addEventListener("touchmove",function(b){ub(b.touches,"move");a(b)},l),B.addEventListener("touchstart",function(b){ub(b.touches,"start");a(b)},l),B.addEventListener("touchend",
function(b){ub(b.changedTouches,"end");a(b)},l)):(B.onmousemove=function(a){a||(a=window.event());E[0].x=a.clientX-B.offsetLeft;E[0].y=a.clientY-B.offsetTop},B.onmousedown=function(b){b||(b=window.event());switch(b.button){case 0:E[0].left=h;break;case 1:E[0].n=h;break;case 2:E[0].right=h}a(b)},B.onmouseup=function(b){b||(b=window.event());switch(b.button){case 0:E[0].left=l;break;case 1:E[0].n=l;break;case 2:E[0].right=l}a(b)},B.onmouseout=function(b){b||(b=window.event());E[0].left=l;E[0].right=
l;E[0].n=l;a(b)},wheel=function(b){var c=0;if(!b)b=window.event;if(b.wheelDelta){c=b.wheelDelta/120;window.opera&&(c=-c)}else b.detail&&(c=-b.detail/3);E[0].s=c>0?1:c<0?-1:0;b.preventDefault&&b.preventDefault();b.returnValue=l;a(b)},window.addEventListener&&window.addEventListener("DOMMouseScroll",wheel,l),window.onmousewheel=document.onmousewheel=wheel);document.onkeydown=B.onkeydown=function(b){b||(b=window.event());jb=h;a(b)};document.onkeyup=B.onkeyup=function(b){b||(b=window.event());a(b)};zb(-1);
Ab(C(0,0,0));wb();try{window.GLB_ON_LOOP?vb("GLB_ON_LOOP"):vb("GLB_MAIN_LOOP")}catch(f){}B.style.cursor="none";tb()}function Cb(a){a instanceof Bb?(Wa[a.h]=a,a.h>=Wa.length&&(Wa.length=a.h+1)):l?(Db[a.h]=a,a.h>=Db.length&&(Db.length=a.h+1)):t("Cannot register unknown object: "+a.constructor)}function C(a,b,c){return 65536*(a%256)+256*(b%256)+c%256}var rb=C(255,255,255),sb=l;function Eb(a,b,c,e,f){A.save();A.fillStyle=Fb(f);A.fillRect(x(a),x(b),x(c),x(e));A.restore()}
function Fb(a){for(a=a.toString(16);6>a.length;)a="00"+a;return"#"+a}function Gb(a,b,c){A.save();A.font="12pt Consolas";A.fillStyle="#ffffff";A.fillText(a,~~(b+0.5),~~(c+0.5)+12);A.restore()}var Db=[];function Touch(){this.y=this.x=this.G=this.F=this.N=this.M=0;this.n=this.right=this.left=l;this.s=0}
function ub(a,b){kb=l;if(a)switch(b){case "start":for(var c=E.length;c<a.length-1;c++){var e=a[c];E[e.identifier].left=h}E.length=a.length;break;case "end":for(c=0;c<a.length;c++)e=a[c],E[e.identifier].left=l;break;case "move":for(c=0;c<a.length;c++)e=a[c],E[e.identifier].left=h,E[e.identifier].x=e.clientX-B.offsetLeft,E[e.identifier].y=e.clientY-B.offsetTop}else for(c=mb=lb=0;c<E.length;c++)if(e=E[c],e.V=e.s,e.s=0,e.F=e.x-e.M,e.G=e.y-e.N,lb+=e.F,mb+=e.G,e.O=e.x,e.P=e.y,e.left||e.right||e.n)kb=h}
function qb(a){if(Va[a])return Va[a].loaded||t("Image not yet loaded '"+a+"'"),Va[a];t("Image not available '"+a+"'")}var pb=l,F=[];function Bb(a,b,c){this.canvas=a;this.l=a.getContext("2d");this.h=b+2;this.r=c;this.l==j&&t("Given buffer does not support '2d'")}function zb(a){var b=Xa;b&&b.r&&(qb(b.r).data=j,qb(b.r).g=j);(Xa=Wa[a+2])?(A=Xa.l,B=Xa.canvas):Xa=b}function Ab(a){A.save();A.fillStyle=Fb(a);A.fillRect(0,0,B.width,B.height);Ya=a;A.restore()}var pa=l;
window.main=function(){N=12;O=8;Hb=0.7;ua(v(P),[~~(N+1),~~(O+1)]);ua(v(Q),[4]);ab=30;R=1;V[0]=0;Y[0]=0;Ib[0]=0;Jb[0]=0;var a=Y;V[0]=B.width;a[0]=B.height;Kb=Lb};window.GLB_ON_MOUSEWAIT=function(){if(kb)throw window.onbeforeunload(),new da;gb=h};window.GLB_ON_MOUSEWAIT=GLB_ON_MOUSEWAIT;
window.GLB_ON_LOOP=function(){var a=0,a=Kb;if(a==Mb){func6_DoMove(Z,R);if(func11_CheckWinner(R,Q)){var a=Z,b=v(Q.b(0).a[p]),c=v(Q.b(2).a[p]);for(a[0]=b<c?b:c;u(Z[0],xa(v(Q.b(0).a[p]),v(Q.b(2).a[p])),1);Z[0]+=1){a=v(Q.b(1).a[p]);b=v(Q.b(3).a[p]);for(local2_my_613=a<b?a:b;u(local2_my_613,xa(v(Q.b(1).a[p]),v(Q.b(3).a[p])),1);local2_my_613+=1)P.b(~~Z[0],~~local2_my_613).a[p]=3}func9_ShowField(V,Y);1==R?func6_MsgBox("You won?"):func6_MsgBox("I won!");wb();vb("GLB_ON_MOUSEWAIT")}R=func10_OtherColor(R);
func9_ShowField(V,Y);1!=R&&func6_MsgBox("Thinking...");wb();Kb=Lb}else if(a==Nb){var a=Z,b=Ob,c=Ib,e=Jb;if(0<E.length){var f=E[0];a[0]=f.x;b[0]=f.y;c[0]=f.left?1:0;e[0]=f.right?1:0}0==Ib[0]&&!Pb?(func9_ShowField(V,Y),"WINCE"!=ja()&&Gb("V",Z[0]-8,v(Ob[0])),Z[0]=Z[0]/V[0]*(N+1),Ob[0]=Ob[0]/Y[0]*(O+1),Gb(ka(func7_RatePos(Z,Ob,R)),0,300),wb(),gb=h):Pb?Pb&&(wb(),Ib[0]||(Z[0]=Z[0]/V[0]*(N+1),Ob[0]=Ob[0]/Y[0]*(O+1),Pb=0,Kb=Mb)):Pb=1}else a==Lb&&(1==R?Kb=Nb:(Z[0]=func7_GetBest(R,1),Kb=Mb))};
window.GLB_ON_LOOP=GLB_ON_LOOP;window.func9_ShowField=function(a,b){var a=v(a),b=v(b),c=0,e=0,f=new ta,k=0,m=0;ua(v(f),[4]);f.b(1).a[p]=C(0,255,128);f.b(2).a[p]=C(128,128,255);f.b(3).a[p]=C(255,255,64);a/=N+1;b/=O+1;for(c=0;u(c,N,1);c+=1)for(e=0;u(e,O,1);e+=1)k=c*a,m=e*b,Eb(v(k),v(m),v(a),v(b),C(255,255,255)),Eb(k+1,m+1,a-2,b-2,v(~~f.b(~~P.b(~~c,~~e).a[p]).a[p]));return 0};
window.func6_DoMove=function(a,b){for(var a=v(a),b=v(b),c=0,c=O;u(c,0,-1);c+=-1)if(0==P.b(~~a,~~c).a[p])return P.b(~~a,~~c).a[p]=b,w(v(c));return w(-1)};window.func8_UnDoMove=function(a){for(var a=v(a),b=0,b=0;u(b,O,1);b+=1)if(0!=P.b(~~a,~~b).a[p])return P.b(~~a,~~b).a[p]=0,w(1);return 0};window.func10_OtherColor=function(a){a=v(a);return 1==a?w(2):w(1)};window.func7_CanMove=function(){for(var a=0,a=0;u(a,N,1);a+=1)if(0==P.b(~~a,1).a[p])return w(1);return 0};
window.func11_CheckWinner=function(a,b){for(var c={skip:1146},a=v(a),b=v(b),e=0,f=0,k=1148;0<=k;)switch(k){case 1148:e=0;case 836:if(!u(e,N,1)){k=839;break}case 1147:f=0;case 845:if(!u(f,O,1)){k=848;break}case 861:if(P.b(~~e,~~f).a[p]==a){k=858;break}case 860:k=c.skip;break;case 858:b.b(0).a[p]=e,b.b(1).a[p]=f;case 1009:if(!(e<N-2)){k=878;break}case 933:if(!(P.b(~~(e+1),~~f).a[p]==a&&P.b(~~(e+2),~~f).a[p]==a&&P.b(~~(e+3),~~f).a[p]==a)){k=915;break}case 924:return b.b(2).a[p]=e+3,b.b(3).a[p]=f,w(1);
case 915:case 1008:if(!(f<O-2)){k=940;break}case 1007:if(!(P.b(~~(e+1),~~(f+1)).a[p]==a&&P.b(~~(e+2),~~(f+2)).a[p]==a&&P.b(~~(e+3),~~(f+3)).a[p]==a)){k=986;break}case 995:return b.b(2).a[p]=e+3,b.b(3).a[p]=f+3,w(1);case 986:case 940:case 878:case 1145:if(!(f<O-2)){k=1016;break}case 1071:if(!(P.b(~~e,~~(f+1)).a[p]==a&&P.b(~~e,~~(f+2)).a[p]==a&&P.b(~~e,~~(f+3)).a[p]==a)){k=1053;break}case 1059:return b.b(2).a[p]=e,b.b(3).a[p]=f+3,w(1);case 1053:case 1144:if(!(3<e)){k=1076;break}case 1143:if(!(P.b(~~(e-
1),~~(f+1)).a[p]==a&&P.b(~~(e-2),~~(f+2)).a[p]==a&&P.b(~~(e-3),~~(f+3)).a[p]==a)){k=1122;break}case 1131:return b.b(2).a[p]=e-3,b.b(3).a[p]=f+3,w(1);case 1122:case 1076:case 1016:case 1146:f+=1;k=845;break;case 848:e+=1;k=836;break;case 839:return 0;default:t("Gotocounter exception pc: "+k)}};window.func5_GetAt=function(a,b){a=v(a);b=v(b);return 0>a||0>b||a>N||b>O?w(-1):w(v(P.b(~~a,~~b).a[p]))};
window.func7_RatePos=function(a,b,c){for(var a=v(a),b=v(b),c=v(c),e=0,f=0,k=0,m=0,n=0,y=0,r=0,q=0,G=0,H=0,f=0;u(f,3,1);f+=1){e=0;e=f;0==e?(m=1,n=0):1==e?(m=0,n=1):2==e?(m=1,n=-1):3==e&&(n=m=1);for(k=H=G=r=q=1;u(k,3,1);k+=1)if(e=func5_GetAt(a+k*m,b+k*n),G&&(e==c?(r+=1,q+=1):0==e?q+=1:G=0),e=func5_GetAt(a-k*m,b-k*n),H)e==c?(r+=1,q+=1):0==e?q+=1:H=0;4>q&&(r=1);if(3<r)return w(1E4);y+=r}return w(v(y))};
window.func8_RateMove=function(a,b,c,e){var a=v(a),b=v(b),c=v(c),e=v(e),f=0;if(2<c||1E4<=e.b(~~b).a[p])return 0;f=func6_DoMove(a,b);if(0>f)return func7_CanMove()?0:w(v(c));e.b(~~b).a[p]=xa(v(e.b(~~b).a[p]),func7_RatePos(a,f,b));e.b(~~b).a[p]=xa(v(e.b(~~b).a[p]),func7_RatePos(a,f,func10_OtherColor(b)));1E4>e.b(~~b).a[p]&&func8_RateMove(func7_GetBest(func10_OtherColor(b),c+1),func10_OtherColor(b),c+1,e);func8_UnDoMove(a);return 0};
window.func7_GetBest=function(a,b){var a=v(a),b=v(b),c=0,e=0,f=0,k=0,m=0,n=new ta;ua(v(n),[3]);c=-1;e=0;if(va(100)>100*Hb)return w(va(v(N)));for(k=0;u(k,N,1);k+=1)if(n.b(~~a).a[p]=0,n.b(~~func10_OtherColor(a)).a[p]=0,f=(1-2*x(~~(k+1)%2))*k/2+x(v(~~k)%2)+(N+x(v(~~N)%2))/2,f=x(f),m=x(f%~~(N+1)),0==P.b(~~m,0).a[p]&&(func8_RateMove(m,a,b,n),1E4<=n.b(~~a).a[p]&&(n.b(~~func10_OtherColor(a)).a[p]=1),f=n.b(~~a).a[p]/n.b(~~func10_OtherColor(a)).a[p],f>e&&(e=f,c=m),func8_RateMove(m,func10_OtherColor(a),b,n),
1E4<n.b(~~func10_OtherColor(a)).a[p]))c=m,e=n.b(~~func10_OtherColor(a)).a[p];0>c&&(c=va(v(N)));return w(v(c))};window.func6_MsgBox=function(a){var a=v(a),b=[0],c=[0],e=0,f=0;ib||(ib=A.measureText("W"))||t("Font metrics unsupported!");b[0]=ib.width;c[0]=ib.height?ib.height:16;e=(V[0]-b[0]*a.length)/2;f=Y[0]/4;b[0]*=a.length;Eb(e-4,f-4,b[0]+8,c[0]+8,C(255,255,255));Eb(e-1,f-1,b[0]+2,c[0]+2,C(0,0,0));Gb(v(a),v(e),v(f));return 0};window.method13_type7_TObject_12_ToString_Str=aa("Object");
window.method13_type7_TObject_6_Equals=function(a,b){a=v(a);b=v(b);return a==b?1:w(0)};window.method13_type7_TObject_10_ToHashCode=aa(0);var Qb={v:method13_type7_TObject_12_ToString_Str,t:method13_type7_TObject_6_Equals,u:method13_type7_TObject_10_ToHashCode};window.type7_TObject=function(){this.k=Qb;return this};window.type7_TObject.prototype.z=function(){var a=new type7_TObject;a.k=this.k;return a};type7_TObject.prototype.v=function(){return this.k.v(this)};
type7_TObject.prototype.t=function(a){return this.k.t(a,this)};type7_TObject.prototype.u=function(){return this.k.u(this)};var Mb=1,Nb=2,Lb=3,Kb=0,Hb=0,V=[0],Y=[0],N=0,O=0,P=new ta,Q=new ta,R=0,Ib=[0],Jb=[0],Z=[0],Ob=[0],Pb=0;window.initStatics=function(){};for(var Tb=0;Tb<preInitFuncs.length;Tb++)preInitFuncs[Tb]();
