"undefined"==typeof preInitFuncs&&(preInitFuncs=[]);preInitFuncs.push(function(){"console"==viewMode&&"undefined"==typeof inEditorPreview&&(document?window.onload=function(a){a=document.createElement("textarea");a.style.width="100%";a.style.height="480px";a.id="GLBCONSOLE";document.body.appendChild(a);updateConsole()}:updateConsole())});var startTime=(new Date).getTime();function GLBException(a,b,c){this.text=a;this.line=c;this.file=b}function GLBExitException(){}
GLBExitException.prototype.toString=function(){return"GLB Exit"};GLBException.prototype.toString=function(){return"Unhandled exception '"+text+"' in file '"+this.file+"' in line'"+this.line+"'"};GLBException.prototype.getText=function(){return this.text};GLBException.prototype.toString=function(){return"Uncought GLBException '"+this.text+"' stacktrace: "+STACKTRACE_Str()};var waitload=0,exec=!1,tmpPositionCache=-1,arrargs=Array(64),consoleOutput,consoleSize=1E4,currentDir,mainCall=!1;
function STDOUT(a){void 0==consoleOutput&&(consoleOutput=document?document.getElementById("GLBCONSOLE"):null);consoleOutput?(consoleOutput.value+=a,consoleOutput.scrollTop=consoleOutput.scrollHeight):console.log(a)}function STDERR(a){STDOUT("Error: "+a)}function STDCOLOR(){}function DEBUG(a){console.log(a)}function END(){window.onbeforeunload();throw new GLBExitException;}function GETTIMERALL(){return(new Date).getTime()-startTime}
function PLATFORMINFO_Str(a){switch(a){case "":return"HTML5";case "DOCUMENTS":case "APPDATA":case "TEMP":return"/";case "ID":return""+uniqueId;case "DEVICE":return"DESKTOP";case "BATTERY":return(a=navigator.battery||window.navigator.battery||navigator.battery||navigator.mozBattery||navigator.webkitBattery)?100*a.level:100;case "TIME":var a=new Date,b=function(a){a=CAST2STRING(a);1==a.length&&(a="0"+a);return a};return b(a.getFullYear())+"-"+b(a.getMonth())+"-"+b(a.getDate())+" "+b(a.getHours())+":"+
b(a.getMinutes())+":"+b(a.getSeconds());case "COMPILED":return rot13(compileTime);case "VERSION":return rot13(userDefVersion);case "HOSTID":return rot13(hostId);case "LOCALE":return navigator.language||window.navigator.userLanguage||window.navigator.language;default:return 6<a.length&&"GLEXT:"==MID_Str(a,0,6)?"0":""}}function GETLASTERROR_Str(){return"0 Successfull"}function SHELLCMD(a,b,c,e){try{e[0]=CAST2FLOAT(eval(a))}catch(f){e[0]=0,e[0]=0,throwError("SHELLCMD raised ab error.")}}
function SHELLEND(a){try{eval(a)}catch(b){throwError("SHELLEND raised an error")}END()}function CALLBYNAME(a){return eval("if (window['"+a+"']) window."+a+"(); else ret = 0;")}var callStack=[];function StackFrame(a,b,c){this.name=a;this.info=b;this.dbg=c}function stackPush(a,b){callStack.push(new StackFrame(a,b,__debugInfo))}function stackPop(){__debugInfo=callStack.pop().dbg}
function stackTrace(){for(var a="",b=callStack.length-1;0<=b;b--)a+="\tin '"+callStack[b].name+"' in file '"+MID_Str(callStack[b].info,INSTR(callStack[b].info,":")+1)+"' in line '"+MID_Str(callStack[b].info,0,INSTR(callStack[b].info,":"))+"'\n";return a}function throwError(a){throw a;}
function formatError(a){a=a.message?a.message:a.toString();0==a.indexOf("GLBERR")&&(a=a.substring(6));if(debugMode)var b=__debugInfo,a="Error:\n '"+a+"' "+("\nAppeared in line '"+MID_Str(b,0,INSTR(b,":"))+"' in file '"+MID_Str(b,INSTR(b,":")+1)+"' "),a=a+("\n\n"+stackTrace());return a}function dumpArray(a){for(var b="",c=!1,e=0;e<a.length;e++)c&&(b+=", "),b+="'"+a[e]+"'",c=!0;return"["+b+"]"}function toCheck(a,b,c){return 0<c?a<=b:0>c?a>=b:!0}function untilCheck(a,b,c){return 0<c?a<b:0>c?a>b:!0}
function isKnownException(a){return a instanceof GLBExitException||a instanceof GLBException}function unref(a){return a instanceof Array?a[0]:a}function ref(a){return a instanceof Array?a:[a]}function tryClone(a){switch(typeof a){case "undefined":case "function":case "string":case "boolean":case "number":break;default:return a instanceof Array?[tryClone(a[0])]:a.clone()}return a}
function updateConsole(){try{(mainCall||(main(),mainCall=!0),!waitload&&!exec)?(exec=!0,"function"==typeof GLB_ON_INIT&&GLB_ON_INIT()):window.requestAnimFrame(updateConsole,100)}catch(a){a instanceof GLBExitException&&alert(formatError(a))}}function castobj(a,b){return a instanceof Array?a[0]instanceof b?a:[eval("new "+b+"()")]:a instanceof b?a:eval("new "+b+"()")}var dataLabel,dataPosition;function RESTORE(a){dataLabel=a;dataPosition=0}
function READ(){var a=dataLabel[dataPosition];dataPosition++;return a}function CAST2INT(a){if(a instanceof Array)return[CAST2INT(a[0])];switch(typeof a){case "function":return 1;case "undefined":throwError("Cannot cast 'undefined'");case "number":return~~a;case "string":return isNaN(a)||""==a?0:parseInt(a,10);case "boolean":return a?1:0;case "object":return CAST2INT(a.toString());default:throwError("Unknown type!")}}function INT2STR(a){return isNaN(a)||""==a?0:parseInt(a,10)}
function INTEGER(a){return CAST2INT(a)}function CAST2FLOAT(a){if(a instanceof Array)return[CAST2FLOAT(a[0])];switch(typeof a){case "function":return 1;case "undefined":throwError("Cannot cast 'undefined'");case "number":return a;case "string":return isNaN(a)||""==a?0:parseFloat(a);case "boolean":return a?1:0;case "object":return CAST2FLOAT(a.toString());default:throwError("Unknown type!")}}function FLOAT2STR(a){return isNaN(a)||""==a?0:parseFloat(a)}function STACKTRACE_Str(){return stackTrace()}
function CAST2STRING(a){if(a instanceof Array)return[CAST2STRING(a[0])];switch(typeof a){case "function":return"1";case "undefined":throwError("Cannot cast undefined to string");case "boolean":return a?"1":"0";case "number":return""+a;case "string":return a;case "object":return a.toString();default:throwError("Unknown type")}}function PUTENV(a,b){localStorage.setItem(("env_"+a).toLowerCase(),b)}function GETENV_Str(a){return localStorage.getItem(("env_"+a).toLowerCase())}
function SLEEP(a){for(var b=GETTIMERALL();GETTIMERALL()-b<a;);}
window.localStorage||Object.defineProperty(window,"localStorage",new function(){var a=[],b={};Object.defineProperty(b,"getItem",{value:function(a){return a?this[a]:null},writable:!1,configurable:!1,enumerable:!1});Object.defineProperty(b,"key",{value:function(b){return a[b]},writable:!1,configurable:!1,enumerable:!1});Object.defineProperty(b,"setItem",{value:function(a,b){a&&(document.cookie=escape(a)+"="+escape(b)+"; path=/")},writable:!1,configurable:!1,enumerable:!1});Object.defineProperty(b,"length",
{get:function(){return a.length},configurable:!1,enumerable:!1});Object.defineProperty(b,"removeItem",{value:function(a){if(a){var b=new Date;b.setDate(b.getDate()-1);document.cookie=escape(a)+"=; expires="+b.toGMTString()+"; path=/"}},writable:!1,configurable:!1,enumerable:!1});this.get=function(){var c,e;for(e in b)c=a.indexOf(e),-1===c?b.setItem(e,b[e]):a.splice(c,1),delete b[e];for(;0<a.length;a.splice(0,1))b.removeItem(a[0]);for(var f=0,g=document.cookie.split(/\s*;\s*/);f<g.length;f++)c=g[f].split(/\s*=\s*/),
1<c.length&&(b[e=unescape(c[0])]=unescape(c[1]),a.push(e));return b};this.configurable=!1;this.enumerable=!0});function NETWEBEND(a){window.location=a;END()}window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
function checkBrowserName(a){return-1<navigator.userAgent.toLowerCase().indexOf(a.toLowerCase())?!0:!1}window.onbeforeunload=function(){CALLBYNAME("GLB_ON_QUIT");saveFileSystem()};function saveFileSystem(){localStorage&&localStorage.setItem("filesystem",fileSystem.save())}function GLBArray(){this.values=[];this.dimensions=[0];this.defval=0;return this}
GLBArray.prototype.clone=function(){var a=new GLBArray;a.dimensions=this.dimensions.slice(0);a.defval=this.defval;switch(typeof this.defval){case "number":case "string":case "boolean":case "function":a.values=this.values.slice(0);break;default:if(void 0!=this.values&&void 0!=this.values.dimensions)for(var b=0;b<this.values.length;b++)a.values[b]=tryClone(this.values[b]);else a.values=[]}return a};
GLBArray.prototype.arrAccess=function(){tmpPositionCache=0;for(var a=arguments.length-1;0<=a;a--){a>=this.dimensions.length&&throwError("Wrong dimension count '"+(arguments.length-1)+"' expected '"+this.dimensions.length+"'");var b=arguments[a];0>b&&(b=this.dimensions[a]+b);(0>b||b>=this.dimensions[a])&&throwError("Array index out of bounds access, position: "+dumpArray(arguments));arrargs[a]=b}switch(arguments.length){case 1:tmpPositionCache=arrargs[0];break;case 2:tmpPositionCache=arrargs[0]+arrargs[1]*
this.dimensions[0];break;case 3:tmpPositionCache=arrargs[0]+arrargs[1]*this.dimensions[0]+arrargs[2]*this.dimensions[0]*this.dimensions[1];break;case 4:tmpPositionCache=arrargs[0]+arrargs[1]*this.dimensions[0]+arrargs[2]*this.dimensions[0]*this.dimensions[1]+arrargs[3]*this.dimensions[0]*this.dimensions[1]*this.dimensions[2];break;default:b=this.values.length/this.dimensions[arguments.length-1];for(a=arguments.length-1;0<=a;a--)tmpPositionCache+=arrargs[a]*b,b/=this.dimensions[a-1]}return this};
function realArrSize(a){var b=1;for(d in a)a[d]=CAST2INT(a[d]),b*=a[d];return b}function DIM(a,b,c){a.values=Array(realArrSize(b));a.dimensions=b;a.defval=c;for(b=0;b<a.values.length;b++)a.values[b]=tryClone(c);return a}
function REDIM(a,b,c){var e=a.values.length,f=!1,g;a.dimensions=b;a.defval!==c&&(f=!0,g=c instanceof Array&&!(a.defval instanceof Array)?1:!(c instanceof Array)&&a.defval instanceof Array?2:0);a.defval=c;a.values.length=realArrSize(b);b=e;f&&(b=0);for(i=b;i<a.values.length;i++)a.values[i]?1==g?a.values[i]=[a.values[i]]:2==g&&(a.values[i]=a.values[i][0]):a.values[i]=tryClone(a.defval);return a}function BOUNDS(a,b){return a.dimensions[b]}
function DIMPUSH(a,b){REDIM(a,[a.values.length+1],a.defval);a.values[a.values.length-1]=tryClone(b)}function DIMDEL(a,b){a.values.splice(b,1);a.dimensions[0]--}function DIMDATA(a,b){a.values=b;a.dimensions=[b.length]}function SEEDRND(a){randomseed=a}function RND(a){if(0==a)return 0;0>a&&(a=-a);return(a+1)*random()}function MIN(a,b){return a<b?a:b}function MAX(a,b){return a>b?a:b}function ABS(a){return Math.abs(a)}function SGN(a){return 0<a?1:0>a?-1:0}function SIN(a){return Math.sin(deg2rad(a))}
function COS(a){return Math.cos(deg2rad(a))}function TAN(a){return Math.tan(deg2rad(a))}function ACOS(a){return Math.acos(deg2rad(a))}function ASIN(a){return Math.asin(deg2rad(a))}function ASL(a,b){return a<<b}function ASR(a,b){return a>>b}function ATAN(a,b){return rad2deg(Math.atan2(a,b))}function bAND(a,b){return a&b}function bOR(a,b){return a|b}function bXOR(a,b){return a^b}function bNOT(a){return~a}function MOD(a,b){return CAST2INT(a%b)}function FMOD(a,b){return a%b}
function FINDPATH(){alert("TODO: findpath")}function LOGN(a){return Math.log(a)}function POW(a,b){return Math.pow(a,b)}function SQR(a){return Math.sqrt(a)}function SWAP(a,b){a[0]=b[0];b[0]=a[0]}function SORTARRAY(a,b){a.values.sort(0==b?function(a,b){a=unref(a);b=unref(b);switch(typeof o){case "undefined":case "function":case "string":case "boolean":case "number":return a<b?-1:a>b?1:0;default:throwError("TODO: Default sortarray with types!")}}:function(a,e){return b([a],[e])})}
function deg2rad(a){return a*(Math.PI/180)}function rad2deg(a){return a*(180/Math.PI)}var randomseed=(new Date).getTime();function random(){randomseed=(9301*randomseed+49297)%233280;return randomseed/233280}function FORMAT_Str(a,b,c){for(var c=CAST2STRING(c),e=INSTR(c,"."),f=REVINSTR(c,"."),g=e;g<a;g++)c=" "+c;for(g=f;g<b;g++)c+="0";for(g=a;g<e;g++)c=MID_Str(c,1);for(g=b;g<f;g++)c=MID_Str(c,0,c.length-1);return c}
function ENCRYPT_Str(a,b){var c=0;for(i=0;i<a.length;i++)c+=ASC(a,i);var c=c%16,e="";for(i=0;i<b.length;i++)e+=CHR_Str(ASC(b,i)+c);return e}function DECRYPT_Str(a,b){var c=0;for(i=0;i<a.length;i++)c+=ASC(a,i);var c=c%16,e="";for(i=0;i<b.length;i++)e+=CHR_Str(ASC(b,i)-c);return e}function LCASE_Str(a){return a.toLowerCase()}function UCASE_Str(a){return a.toUpperCase()}
function MID_Str(a,b,c){try{return-1==c?a.substr(b):a.substr(b,c)}catch(e){throwError("string error (MID$): '"+a+"' start: '"+b+"' count: '"+c+"'")}}function LEFT_Str(a,b){try{return a.substr(0,b)}catch(c){throwError("string error (LEFT$): '"+a+"' count: '"+b+"'")}}function RIGHT_Str(a,b){try{return a.substr(a.length-b,b)}catch(c){throwError("string error (RIGHT$): '"+a+"' count: '"+b+"'")}}function INSTR(a,b,c){return-1==c?a.indexOf(b):a.indexOf(b,c)}
function REVINSTR(a,b,c){return-1==c?a.lastIndexOf(b):a.lastIndexOf(b,c)}function CHR_Str(a){return String.fromCharCode(a)}function REPLACE_Str(a,b,c){for(var e=0;;){e=a.indexOf(b,e);if(-1==e)break;a=a.substring(0,e)+c+a.substring(e+b.length);e+=c.length}return a}function TRIM_Str(a,b){return LTRIM_Str(RTRIM_Str(a,b),b)}function LTRIM_Str(a,b){for(i=0;i<a.length;i++){var c=a.charAt(i);if(-1==b.indexOf(c))return a.substr(i)}return""}
function RTRIM_Str(a,b){for(i=a.length-1;0<=i;i--){var c=a.charAt(i);if(-1==b.indexOf(c))return a.substr(0,i+1)}return""}function ASC(a,b){try{return a.charCodeAt(b)}catch(c){throwError("string error (ASC): '"+a+"' index: '"+b+"'")}}
function SPLITSTR(a,b,c,e){try{var f=0;REDIM(b,[0],b.defval);for(var g=0;g<=a.length;g++){var h=a.charAt(g);if(-1!=c.indexOf(h)||g==a.length){var k=MID_Str(a,f,g-f);if(""!=k||!e)b.defval instanceof Array?DIMPUSH(b,[k]):DIMPUSH(b,k);f=g+1}}return c.length}catch(j){throwError("string error (SPLITSTR): '"+str+"' split: '"+c+"' dropEmpty: "+e)}}function URLENCODE_Str(a){return encodeURI(a)}function URLDECODE_Str(a){return decodeURI(a)}
function createXMLHttpRequest(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){}throwError("XMLHttpRequest not supported");return null}function loadText(a){var b=createXMLHttpRequest();"/"==a.charAt(0)&&(a=a.substring(1));b.open("get",a,!1);b.requestType="text";b.send(null);return b.responseText}var fileSystem=new VirtualFileSystem(localStorage?localStorage.getItem("filesystem"):""),staticFileSystem=new VirtualFileSystem,text=loadText("DIR_STRUCTURE");
if(null==text)throwError("Cannot load dir structure!");else for(var lines=text.split("\n"),pos=0;pos<lines.length;pos++){var line=lines[pos];if(-1!=line.indexOf(":")){var command=line.substring(0,line.indexOf(":")),param=line.substring(line.indexOf(":")+1);switch(command){case "var":if(-1!=param.indexOf("=")){var name=param.substring(0,param.indexOf("=")),value=param.substring(param.indexOf("=")+1);"undefined"==typeof isInWebWorker?window[name]=value:eval(name+" = '"+value+"'")}else throwError("Expecting '='");
break;case "folder":fileSystem.createDir(param);staticFileSystem.createDir(param);break;case "static":staticFileSystem.createFile(param,[]);break;case "editable":staticFileSystem.createFile(param,function(a){var b=loadText(a.path+".GLBSCRIPT_DATA");a.data=b.split(",");return a.data});break;default:throwError("Unknown command '"+command+"'")}}}var channels=[];function GENFILE(){for(var a=0;a<channels.length;a++)if(!channels[a])return a;return channels.length}
function rawpath(a,b){for(var a=(TRIM_Str(b.getFileSystem().getCurrentDir()," ")+TRIM_Str(a," ")).toLowerCase(),c=0,e=b,f=0;f<a.length;f++)switch(a.charAt(f)){case "/":0<f?(c=a.substr(c,f-c),e=e.getSubDir(c),c=f+1):c=1;break;case ".":var g=function(){f++;return f<a.length};if(!g())break;if("."==a.charAt(f)){e=e.getParent();if(!g())break;"/"!=a.charAt(f)&&throwError("Expecting '/'");c=f+1}else"/"==a.charAt(f)&&(c=f+1)}return new FilePointer(a.substr(c,a.length-c),e)}
function FilePointer(a,b){this.name=a;this.dir=b}
function VirtualFileSystem(a){this.mainDir=new VirtualDirectory("",null,this);this.curDir="";this.copyFile=function(a,c){if(this.doesFileExist(form)){var e=this.getFile(a).getData();this.createFile(c,e)}};this.getCurrentDir=function(){return this.curDir};this.setCurrentDir=function(a){"/"!=RIGHT_Str(a,1)&&(a+="/");this.curDir=a};this.getFile=function(a){a=rawpath(a,this.mainDir);return a.dir.getFile(a.name)};this.getDir=function(a){return rawpath(a,this.mainDir).dir};this.doesFileExist=function(a){try{var c=
rawpath(a,this.mainDir);return c.dir.doesFileExist(c.name)}catch(e){}return!1};this.doesDirExist=function(a){try{var c=rawpath(a,this.mainDir);return c.dir.doesDirExist(c.name)}catch(e){}return!1};this.removeFile=function(a){a=rawpath(a,this.mainDir);a.dir.removeFile(a.name)};this.removeDir=function(a){a=rawpath(a,this.mainDir);a.dir.removePath(a.name)};this.createFile=function(a,c){if(this.doesFileExist(a)){var e=this.getFile(a);e.data=c;return e}e=rawpath(a,this.mainDir);return e.dir.createFile(a,
e.name,c)};this.cD=this.createDir=function(a){if(this.doesDirExist(a))return this.getDir(a);a=rawpath(a,this.mainDir);return a.dir.createDir(a.name)};this.cF=this.createFile;this.getMainDir=function(){return this.mainDir};this.save=function(){return this.mainDir.save()};void 0!=a&&(window.filesystem=this,eval(REPLACE_Str(a,"t.","window.filesystem.")))}
function VirtualDirectory(a,b,c){this.name=a;this.parent=b;this.subDirs=[];this.files=[];this.fileSystem=c;this.getList=function(){return this.subDirs.concat(this.files)};this.getFileSystem=function(){return this.fileSystem};this.doesDirExist=function(a){for(var b=0;b<this.subDirs.length;b++)if(this.subDirs[b].name==a)return!0;return!1};this.doesFileExist=function(a){for(var b=0;b<this.files.length;b++)if(this.files[b].name==a)return!0;return!1};this.removeFile=function(a){for(var b=0;b<this.files.length;b++)if(this.files[b].name==
a){this.files.splice(b,1);return}throwError("FileNotFound "+a)};this.removeDir=function(a){for(var b=0;b<this.subDirs.length;b++)if(this.subDirs[b].name==a){this.subDirs.splice(b,1);return}throwError("DirNotFound "+a)};this.createDir=function(a){a=new VirtualDirectory(a,this,this.fileSystem);this.subDirs.push(a);return a};this.createFile=function(a,b,c){a=new VirtualFile(this,b,c,a);this.files.push(a);return a};this.getFile=function(a){for(var b=0;b<this.files.length;b++)if(this.files[b].name==a)return this.files[b];
throwError("file not found")};this.getDir=function(a){for(var b=0;b<this.subDirs.length;b++)if(this.subDirs[b].name==a)return this.subDirs[b];throwError("Dir not found")};this.getSubDir=function(a){for(var b=0;b<this.subDirs.length;b++)if(this.subDirs[b].name==a)return this.subDirs[b];throwError("Dir not found: "+a)};this.getParent=function(){return this.parent};this.getPath=function(){return(this.getParent()?this.getParent().getPath()+"/":"")+this.name};this.save=function(){var a="";null!=this.getParent()&&
(a='t.cD("'+this.getPath()+'");\n');for(var b=0;b<this.files.length;b++)a+=this.files[b].save();for(b=0;b<this.subDirs.length;b++)a+=this.subDirs[b].save();return a}}function VirtualFile(a,b,c,e){this.name=b;this.data=c;this.dir=a;this.path=e;this.getName=function(){return this.name};this.getData=function(){return"function"==typeof this.data?this.data(this):this.data};this.save=function(){return't.cF("'+this.dir.getPath()+"/"+this.name+'", '+JSON.stringify(this.getData())+");\n"}}
function Channel(a,b,c){this.channel=a;this.mode=c;this.ptr=0;b=b.toLowerCase();if(fileSystem.doesFileExist(b))this.file=fileSystem.getFile(b);else if(staticFileSystem.doesFileExist(b))1==c?this.file=staticFileSystem.getFile(b):(a=staticFileSystem.getFile(b),this.file=fileSystem.createFile(b,a.getData()));else if(1!=c)try{this.file=fileSystem.createFile(b,[])}catch(e){throwError("cannot create file: "+b)}else throwError("file not found: "+b);-1==c&&(this.ptr=this.file.getData().length);this.updateSize=
function(){if(this.ptr>this.file.getData().length)this.file.getData().length=this.ptr};this.checkPosition=function(){this.ptr>this.file.getData().length&&throwError("Reached end of file: '"+this.ptr+"' filesize: '"+this.file.getData().length+"'")};this.ENDOFFILE=function(){return this.ptr>=this.file.getData().length||this.ptr<0};this.FILESEEK=function(a,b){switch(b){case -1:this.ptr=this.file.getData().length-a;break;case 0:this.ptr=a;break;case 1:this.ptr=this.ptr+a}if(this.ENDOFFILE())this.ptr=
this.file.getData().length};this.READLINE=function(){for(var a="",b="";(b=String.fromCharCode(this.file.getData()[this.ptr]))!="\n"&&this.ptr<this.file.getData().length;){a=a+b;this.ptr++}this.checkPosition();this.ptr++;a.substr(a.length-1,1)=="\r"&&(a=a.substr(0,a.length-1));return a};this.READBYTE=function(){this.ptr++;var a=new Int8Array(1);a[0]=this.file.getData()[this.ptr-1];this.checkPosition();return a[0]};this.READUBYTE=function(){this.ptr++;var a=new Uint8Array(1);a[0]=this.file.getData()[this.ptr-
1];this.checkPosition();return a[0]};this.READWORD=function(){this.ptr=this.ptr+2;var a=new ArrayBuffer(2),b=new Uint8Array(a);b[0]=this.file.getData()[this.ptr-2];b[1]=this.file.getData()[this.ptr-1];a=new Int16Array(a);this.checkPosition();return a[0]};this.READUWORD=function(){this.ptr=this.ptr+2;var a=new ArrayBuffer(2),b=new Uint8Array(a);b[0]=this.file.getData()[this.ptr-2];b[1]=this.file.getData()[this.ptr-1];a=new Uint16Array(a);this.checkPosition();return a[0]};this.READLONG=function(){this.ptr=
this.ptr+4;var a=new ArrayBuffer(4),b=new Uint8Array(a);b[0]=this.file.getData()[this.ptr-4];b[1]=this.file.getData()[this.ptr-3];b[2]=this.file.getData()[this.ptr-2];b[3]=this.file.getData()[this.ptr-1];a=new Int32Array(a);this.checkPosition();return a[0]};this.READULONG=function(){this.ptr=this.ptr+4;var a=new ArrayBuffer(4),b=new Uint8Array(a);b[0]=this.file.getData()[this.ptr-4];b[1]=this.file.getData()[this.ptr-3];b[2]=this.file.getData()[this.ptr-2];b[3]=this.file.getData()[this.ptr-1];a=new Uint32Array(a);
this.checkPosition();return a[0]};this.READIEEE=function(){this.ptr=this.ptr+8;var a=new ArrayBuffer(8),b=new Uint8Array(a);b[0]=this.file.getData()[this.ptr-8];b[1]=this.file.getData()[this.ptr-7];b[2]=this.file.getData()[this.ptr-6];b[3]=this.file.getData()[this.ptr-5];b[4]=this.file.getData()[this.ptr-4];b[5]=this.file.getData()[this.ptr-3];b[6]=this.file.getData()[this.ptr-2];b[7]=this.file.getData()[this.ptr-1];a=new Float64Array(a);this.checkPosition();return a[0]};this.READSHORTIEEE=function(){this.ptr=
this.ptr+4;var a=new ArrayBuffer(4),b=new Uint8Array(a);b[0]=this.file.getData()[this.ptr-4];b[1]=this.file.getData()[this.ptr-3];b[2]=this.file.getData()[this.ptr-2];b[3]=this.file.getData()[this.ptr-1];a=new Float32Array(a);this.checkPosition();return a[0]};this.READSTR=function(a){for(var b="",c=0;c<a;c++)b=b+CHR_Str(this.READUBYTE());return b};this.WRITEBYTE=function(a){var b=new Int8Array(1);b[0]=a;this.file.getData()[this.ptr]=b[0];this.ptr++;this.updateSize()};this.WRITEUBYTE=function(a){var b=
new Uint8Array(1);b[0]=a;this.file.getData()[this.ptr]=b[0];this.ptr++;this.updateSize()};this.WRITEWORD=function(a){var b=new ArrayBuffer(2);(new Int16Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITEUWORD=function(a){var b=new ArrayBuffer(2);(new Uint16Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITELONG=function(a){var b=new ArrayBuffer(4);(new Int32Array(b))[0]=a;a=new Uint8Array(b);
for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITEULONG=function(a){var b=new ArrayBuffer(4);(new Uint32Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITEIEEE=function(a){var b=new ArrayBuffer(8);(new Float64Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITESHORTIEEE=function(a){var b=new ArrayBuffer(4);(new Float32Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<
a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITESTR=function(a){for(var b=0;b<a.length;b++)this.WRITEUBYTE(ASC(a,b));this.updateSize()};this.WRITELINE=function(a){this.WRITESTR(a+"\r\n")}}function OPENFILE(a,b,c){try{return channels[a]=new Channel(a,b,c),a>=channels.length&&(channels.length=a+1),1}catch(e){return 0}}function getChannel(a){channels[a]||throwError("Cannot find channel: "+a);return channels[a]}function ENDOFFILE(a){return getChannel(a).ENDOFFILE()?1:0}
function FILEPOSITION(a){return getChannel(a).ptr}function FILESEEK(a,b,c){getChannel(a).FILESEEK(b,c)}function KILLFILE(a){try{fileSystem.doesDirExist(a)?fileSystem.removeDir(a):fileSystem.doesFileExist(a)&&fileSystem.removeFile(a)}catch(b){}try{staticFileSystem.doesDirExist(a)?staticFileSystem.removeDir(a):staticFileSystem.doesFileExist(a)&&staticFileSystem.removeFile(a)}catch(c){}}function CLOSEFILE(a){channels[a]=null;saveFileSystem()}function READUBYTE(a,b){b[0]=getChannel(a).READUBYTE()}
function READBYTE(a,b){b[0]=getChannel(a).READBYTE()}function READWORD(a,b){b[0]=getChannel(a).READWORD()}function READUWORD(a,b){b[0]=getChannel(a).READUWORD()}function READLONG(a,b){b[0]=getChannel(a).READLONG()}function READULONG(a,b){b[0]=getChannel(a).READULONG()}function READSHORTIEEE(a,b){b[0]=getChannel(a).READSHORTIEEE()}function READIEEE(a,b){b[0]=getChannel(a).READIEEE()}function READLINE(a,b){b[0]=getChannel(a).READLINE()}function READSTR(a,b,c){b[0]=getChannel(a).READSTR(c)}
function WRITEUBYTE(a,b){getChannel(a).WRITEUBYTE(b)}function WRITEBYTE(a,b){getChannel(a).WRITEBYTE(b)}function WRITEWORD(a,b){getChannel(a).WRITEWORD(b)}function WRITEUWORD(a,b){getChannel(a).WRITEUWORD(b)}function WRITELONG(a,b){getChannel(a).WRITELONG(b)}function WRITEULONG(a,b){getChannel(a).WRITEULONG(b)}function WRITESHORTIEEE(a,b){getChannel(a).WRITESHORTIEEE(b)}function WRITEIEEE(a,b){getChannel(a).WRITEIEEE(b)}function WRITELINE(a,b){getChannel(a).WRITELINE(b)}
function WRITESTR(a,b){getChannel(a).WRITESTR(b)}function SETSHOEBOX(){}function GETCOMMANDLINE_Str(){var a=window.location.href,b=INSTR(a,"?");return-1==b?"":REPLACE_Str(MID_Str(a,b+1),"&"," ")}function GETCURRENTDIR_Str(){return fileSystem.getCurrentDir()}function SETCURRENTDIR(a){if(""!=a){var a=rawpath(a,fileSystem.getMainDir()).dir.getPath()+a,b=!1,c=!1;try{fileSystem.setCurrentDir(a),b=!0}catch(e){}try{staticFileSystem.setCurrentDir(a),c=!0}catch(f){}return b&&c?1:0}}
function DOESFILEEXIST(a){return fileSystem.doesFileExist(a)||staticFileSystem.doesFileExist(a)?1:0}function DOESDIREXIST(a){return fileSystem.doesDirExist(a)||staticFileSystem.doesDirExist(a)?1:0}function GETFILESIZE(a){try{var b=null;fileSystem.doesFileExist(a)?b=fileSystem.getFile(a):staticFileSystem.doesFileExist(a)?b=staticFileSystem.getFile(a):throwError("Cannot find file: "+a);if(b)return b.getData().length}catch(c){}return 0}
function GETFILELIST(a,b){try{REDIM(b,[0],b.defval);var c=fileSystem.getDir("").getList().concat(staticFileSystem.getDir("").getList()),e=0,f=0,g=[];g.push(".");g.push("..");for(var h=0;h<c.length;h++){var k=c[h],j;a:{for(var l=k.name,m=0,p=0,p=0;p<=a.length;p++){var r=a.charAt(p);switch(r){case "*":p++;var n=a.charAt(p);for(p--;l.charAt(m)!=n&&m<l.length;)m++;break;case "?":m++;break;default:if(r!=l.charAt(m)){j=!1;break a}m++}}j=!0}j&&(k instanceof VirtualDirectory?e++:k instanceof VirtualFile?
f++:throwError("Unknown file type"),g.push(k.name))}for(h=0;h<g.length;h++)b.defval instanceof Array?DIMPUSH(b,[g[h]]):DIMPUSH(b,g[h]);return 4096*e+f}catch(q){throwError("GETFILELIST error: find: '"+a+"'")}}function COPYFILE(a,b){fileSystem.copyFile(a,b);staticFileSystem.copyFile(a,b)}function CREATEDIR(a){try{return fileSystem.createDir(a),staticFileSystem.createDir(a),1}catch(b){}return 0}
function INI(a){this.parse=function(a){try{for(var b=a.replace("\r").split("\n"),c="",e=0;e<b.length;e++){var j=b[e];-1!=INSTR(j,";")&&(j=MID_Str(j,0,INSTR(j,";")));if("["==MID_Str(j,0,1))c=MID_Str(j,1,REVINSTR(j,"]")-1);else if(-1!=INSTR(j,"=")){var l=MID_Str(j,0,INSTR(j,"=")),m=MID_Str(j,INSTR(j,"=")+1);INIPUT(c,l,m)}}}catch(p){throwError("INI parse error: '"+NaN*a)}};this.put=function(a,b,c){try{for(var a=a.toLowerCase(),e,j=0;j<this.cats.length;j++)if(this.cats[j].name==a){e=this.cats[j];if(""==
b&&""==c){this.cats.splice(j,1);return}break}e||(e=new INICat(a),this.cats.push(e));e.put(b,c)}catch(l){throwError("INIPUT error cat: '"+a+"' key: '"+b+"' value: '"+c+"'")}};this.get=function(a,b){try{for(var a=a.toLowerCase(),c,e=0;e<this.cats.length;e++)if(this.cats[e].name==a){c=this.cats[e];break}c||(c=new INICat(a));return c.get(b)}catch(j){throwError("INIGET error cat: '"+a+"' key: '"+b+"'")}};this.save=function(){for(var a="",b=0;b<this.cats.length;b++)a+="["+this.cats[b].name+"]\n",a+=this.cats[b].save();
return a};this.cats=[];this.channel=2674;try{OPENFILE(this.channel,a,0);var b=GETFILESIZE(a);if(0<b){var c=[""];READSTR(this.channel,c,b);b=curIni;curIni=this;this.parse(c[0]);curIni=b}}catch(e){throwError("INI load error: '"+a+"'")}}
function INICat(a){this.name=a;this.keys=[];this.put=function(a,c){for(var a=a.toLowerCase(),e,f=0;f<this.keys.length;f++)if(this.keys[f].key==a){e=this.keys[f];if(""==c){this.keys.splice(f,1);return}break}e||(e=new INIKeyValue(a,c),this.keys.push(e))};this.get=function(a){for(var a=a.toLowerCase(),c,e=0;e<this.keys.length;e++)if(this.keys[e].key==a){c=this.keys[e];break}c||(c=new INIKeyValue(a,""),this.keys.push(c));return c.value};this.save=function(){for(var a="",c=0;c<this.keys.length;c++)a+=
this.keys[c].key+"="+this.keys[c].value+"\n";return a}}function INIKeyValue(a,b){this.key=a;this.value=b}var curIni=null;function INIOPEN(a){if(curIni){var b=curIni.save();WRITESTR(curIni.channel,b);CLOSEFILE(curIni.channel)}curIni=""==a?null:new INI(a)}function INIPUT(a,b,c){curIni&&curIni.put(a,b,c)}function INIGET_Str(a,b){if(curIni)return curIni.get(a,b)}"undefined"==typeof preInitFuncs&&(preInitFuncs=[]);
preInitFuncs.push(function(){if("2d"==viewMode||"undefined"!=typeof inEditorPreview)"undefined"==typeof window&&(window={}),window.onload=function(){"undefined"==typeof GFX_WIDTH&&(window.GFX_WIDTH=640);"undefined"==typeof GFX_HEIGHT&&(window.GFX_HEIGHT=480);var a=document.createElement("canvas");a.width=GFX_WIDTH;a.height=GFX_HEIGHT;a.id="GLBCANVAS";document.body.appendChild(a);init2D("GLBCANVAS")}});
var sprites=[],screens=[],waitload=0,curScreen=null,context=null,canvas=null,clrColor=RGB(0,0,0),keyInput=[],fontbuffer=null,backbuffer=null,initCalled=!1,lastShwscrn=0,showFPS=-1,framePrev=0,frameDelay=0,canvasWidth,canvasHeight,background=null,loopFunc=null,loops=[],usedSoundformat="ogg",hibernate=!1,transCol=null,setBmp=null,currentMouse=0,metrics=null,noSound=!1,anyKeyPress=!1,anyMousePress=!1,globalSpeedX,globalSpeedY,touches=[],touchable=document?"createTouch"in document:!1,doCurrentFunction=
function(){waitload?GLB_ON_LOADING&&GLB_ON_LOADING():loopFunc();inPoly&&ENDPOLY();inViewport&&(context.restore(),inViewport=!1)};
function update2D(){try{if(initCalled){setBmp&&(setBmp(),setBmp=null);updateTouches();if(hibernate){if(ANYMOUSE()||ANYKEY()||globalSpeedX||globalSpeedY)hibernate=!1}else if(canvasWidth=canvas.width,canvasHeight=canvas.height,-1==showFPS)doCurrentFunction();else{var a=GETTIMERALL(),b=a-framePrev;b>=frameDelay&&(doCurrentFunction(),frameDelay=showFPS,b>frameDelay&&(frameDelay-=b-frameDelay),framePrev=a)}anyKeyPress=!1}else initCalled=!0,main();window.requestAnimFrame(update2D,frontbuffer.canvas)}catch(c){c instanceof
GLBExitException||alert(formatError(c))}}function domExceptionError(a){if(a instanceof DOMException)18==a.code?throwError("Cannot access to ressource (maybe pixel data?). If you use Chrome, please run in localhost or use another browser!"):throwError("Unknown DOM error :(");else throw a;}function PUSHLOOP(a){var b=eval("window['"+a+"']");void 0==b&&(loopFunc=function(){throwError("Call to undefined loop!")},throwError("Cannot push undefined loop: '"+a+"'"));loopFunc=b;loops.push([b,a])}
function POPLOOP(){loops.pop();0==loops.length&&throwError("Cannot pop loop, because loop stack is empty!");loopFunc=loops[loops.length-1][0]}function GETCURRENTLOOP_Str(){return loops[loops.length-1][1]}function RETURNTOLOOP(a){for(void 0==eval("window."+a)&&throwError("Cannot return to undefined loop: '"+a+"'");GETCURRENTLOOP_Str()!=a;)POPLOOP()}function X_MAKE2D(){}
function SHOWSCREEN(){lastShwscrn=GETTIMERALL();initCalled&&(USESCREEN(-2),CLEARSCREEN(clrColor),USESCREEN(-1),frontbuffer.context.drawImage(backbuffer.canvas,0,0),CLEARSCREEN(clrColor),background&&backbuffer.context.drawImage(background,0,0))}
function init2D(a){function b(a){a.stopPropagation?(a.stopPropagation(),a.preventDefault()):(a.cancelBubble=!0,a.returnValue=!1)}var c=document.createElement("audio"),e=!1,f=!1;c.canPlayType&&(e=!!c.canPlayType&&""!=c.canPlayType("audio/mpeg"),e="maybe"==e||"probably"==e||!0==e?!0:!1,f=!!c.canPlayType&&""!=c.canPlayType('audio/ogg; codecs="vorbis"'),f="maybe"==f||"probably"==f||!0==f?!0:!1);!f&&!e&&(noSound=!0,console.log("No sound playback possible!"));usedSoundFormat=f?"ogg":"mp3";frontbuffer=new Screen(document.getElementById(a),
-2);register(frontbuffer);a=document.createElement("canvas");a.width=frontbuffer.canvas.width;a.height=frontbuffer.canvas.height;backbuffer=new Screen(a,-1);register(backbuffer);"undefined"==typeof GLB_ON_LOADING&&(GLB_ON_LOADING=null);USESCREEN(-2);context||(throwError("Canvas unsupported, please use a newer browser."),END());canvas.oncontextmenu=function(){return false};touches.push(new Touch);touchable?(canvas.addEventListener("touchmove",function(a){updateTouches(a.touches,"move");b(a)},!1),canvas.addEventListener("touchstart",
function(a){updateTouches(a.touches,"start");b(a)},!1),canvas.addEventListener("touchend",function(a){updateTouches(a.changedTouches,"end");b(a)},!1)):(canvas.onmousemove=function(a){a||(a=window.event());touches[0].x=a.clientX-canvas.offsetLeft;touches[0].y=a.clientY-canvas.offsetTop},canvas.onmousedown=function(a){a||(a=window.event());switch(a.button){case 0:touches[0].left=true;break;case 1:touches[0].middle=true;break;case 2:touches[0].right=true}b(a)},canvas.onmouseup=function(a){a||(a=window.event());
switch(a.button){case 0:touches[0].left=false;break;case 1:touches[0].middle=false;break;case 2:touches[0].right=false}b(a)},canvas.onmouseout=function(a){a||(a=window.event());touches[0].left=false;touches[0].right=false;touches[0].middle=false;b(a)},wheel=function(a){var c=0;if(!a)a=window.event;if(a.wheelDelta){c=a.wheelDelta/120;window.opera&&(c=-c)}else a.detail&&(c=-a.detail/3);touches[0].wheel=c>0?1:c<0?-1:0;a.preventDefault&&a.preventDefault();a.returnValue=false;b(a)},window.addEventListener&&
window.addEventListener("DOMMouseScroll",wheel,!1),window.onmousewheel=document.onmousewheel=wheel);document.onkeydown=canvas.onkeydown=function(a){a||(a=window.event());anyKeyPress=keyInput[a.keyCode]=true;b(a)};document.onkeyup=canvas.onkeyup=function(a){a||(a=window.event());keyInput[a.keyCode]=false;b(a)};USESCREEN(-1);CLEARSCREEN(RGB(0,0,0));SHOWSCREEN();try{window.GLB_ON_LOOP?PUSHLOOP("GLB_ON_LOOP"):PUSHLOOP("GLB_MAIN_LOOP")}catch(g){}SYSTEMPOINTER(0);update2D()}
function deInit2D(){context=canvas=null;sprites=[];screens=[];waitload=0;curScreen=null;clrColor=RGB(0,0,0);keyInput=[];backbuffer=fontbuffer=null;initCalled=!1}
function register(a){a instanceof Sprite?(sprites[a.num]=a,a.num>=sprites.length&&(sprites.length=a.num+1)):a instanceof Screen?(screens[a.num]=a,a.num>=screens.length&&(screens.length=a.num+1)):a instanceof Sound?(sounds[a.num]=a,a.num>=sounds.length&&(sounds.length=a.num+1)):a instanceof SoundChannel?(soundChannels[a.num]=a,a.num>=soundChannels.length&&(soundChannels.length=a.num+1)):throwError("Cannot register unknown object: "+a.constructor);return a.num}
function FOCEFEEDBACK(a,b){var c=navigator.vibrate||navigator.mozVibrate;c&&c(b)}function GETTIMER(){return GETTIMERALL()-lastShwscrn}function ALPHAMODE(){}function SETPIXEL(a,b,c){DRAWRECT(a,b,1,1,c)}function LIMITFPS(a){showFPS=a}function RGB(a,b,c){return 65536*(a%256)+256*(b%256)+c%256}var whiteRGB=RGB(255,255,255);function SETTRANSPARENCY(a){transCol=a}function SMOOTHSHADING(){}function SETSCREEN(a,b){canvas.width=a;canvas.height=b}var inViewport=!1;
function VIEWPORT(a,b,c,e){inViewport&&(context.restore(),inViewport=!1);if(0!=a||0!=b||0!=c||0!=e)context.save(),context.beginPath(),context.rect(a,b,c,e),context.clip(),inViewport=!0}function ALLOWESCAPE(){throwError("TODO: allowescape")}function AUTOPAUSE(){throwError("TODO: autopause")}function HIBERNATE(){hibernate=!0}function GETSCREENSIZE(a,b){a[0]=canvas.width;b[0]=canvas.height}
function GETSPRITESIZE(a,b,c){b[0]=0;c[0]=0;sprites[a]&&sprites[a].loaded&&(b[0]=sprites[a].img.width,c[0]=sprites[a].img.height)}function GETDESKTOPSIZE(a,b){a[0]=window.innerWidth;b[0]=window.innerHeight}function GETFONTSIZE(a,b){metrics||(metrics=context.measureText("W"))||throwError("Font metrics unsupported!");a[0]=metrics.width;b[0]=metrics.height?metrics.height:16}function ISFULLSCREEN(){throwError("TODO: isfullscreen")}
function GETPIXEL(a,b){var c=4*a+4*b*canvas.width;throwError("TODO: getpixel");return RGB(c,c+1,c+2)}function SAVEBMP(){throwError("TODO: savebmp")}function SAVESPRITE(){throwError("TODO: savesprite")}function DRAWLINE(a,b,c,e,f){context.save();context.strokeStyle=formatColor(f);context.beginPath();context.moveTo(CAST2INT(a),CAST2INT(b));context.lineTo(CAST2INT(c),CAST2INT(e));context.stroke();context.restore()}
function DRAWRECT(a,b,c,e,f){context.save();context.fillStyle=formatColor(f);context.fillRect(CAST2INT(a),CAST2INT(b),CAST2INT(c),CAST2INT(e));context.restore()}function formatColor(a){for(a=a.toString(16);6>a.length;)a="00"+a;return"#"+a}function PRINT(a,b,c){context.save();context.font="12pt Consolas";context.fillStyle="#ffffff";context.fillText(a,~~(b+0.5),~~(c+0.5)+12);context.restore()}function SETFONT(){throwError("TODO: setfont")}function LOOPMOVIE(){throwError("TODO: loopmovie")}
function PLAYMOVIE(){throwError("TODO:playmovie")}var sounds=[],soundChannels=[];function genSoundChannel(){for(var a=1;a<soundChannels.length;a++)if(!soundChannels[a])return a;return soundChannels.length+1}
function Sound(a,b,c){this.num=b;this.file=a;this.loaded=!1;this.buffers=[];this.buffers.length=c;this.sound=new Audio(a);this.sound.load();waitload++;var e=this;this.sound.addEventListener("onerror",function(){waitload--;""!=a&&"0"!=a&&throwError("Sound '"+b+"' '"+a+"' not found!")},!1);this.sound.addEventListener("canplaythrough",function(){if(!e.loaded){waitload--;for(var a=0;a<e.buffers.length;a++)e.buffers[a]=new SoundChannel(this)}e.loaded=!0},!1)}
function SoundChannel(a){this.sound=a.cloneNode(!0);this.sound.load();this.num=genSoundChannel();this.playing=this.loaded=!1;this.playTime=0;this.play=function(){this.playing&&this.stop();this.sound.currentTime=0;this.playing=!0;this.playTime=GETTIMERALL();this.sound.play()};this.stop=function(){this.sound.pause();this.sound.currentTime=0;this.playing=!1;this.playTime=0};var b=this;this.sound.addEventListener("canplaythrough",function(){b.loaded||waitload--;b.loaded=!0},!1);this.sound.addEventListener("ended",
function(){b.stop()},!1);waitload++}function LOADSOUND(a,b,c){if(!noSound){var e=REPLACE_Str(MID_Str(a,MAX(0,a.lastIndexOf("/")),-1),"/",""),a=REPLACE_Str(a,e,".html5_convertedsounds_"+e)+"/",a=new Sound("./"+("ogg"==usedSoundFormat?a+"sound.ogg":a+"sound.mp3"),b,c);register(a);return a}}
function PLAYSOUND(a){if(!noSound){if(a=sounds[a]){for(var b=null,c=GETTIMERALL()+1,e=0;e<a.buffers.length&&0!=c;e++)a.buffers[e].playTime<c&&(c=a.buffers[e].playTime,b=a.buffers[e]);b?b.play():throwError("No channel available...");return b.num}return 0}}function HUSH(){if(!noSound)for(var a=0;a<soundChannels.length;a++)soundChannels[a]&&soundChannels[a].playing&&soundChannels[a].stop()}function SOUNDPLAYING(a){return noSound?!1:soundChannels[a]&&soundChannels[a].playing?0:1}
function PLAYMUSIC(){}function STOPMUSIC(){noSound||SOUNDPLAYING(0)&&soundChannels[0].stop()}function ISMUSICPLAYING(){return noSound?!1:SOUNDPLAYING(0)}function Touch(){this.y=this.x=this.speedy=this.speedx=this.lasty=this.lastx=0;this.middle=this.right=this.left=!1;this.reallywheel=this.wheel=0}
function updateTouches(a,b){anyMousePress=!1;if(a)switch(b){case "start":for(var c=touches.length;c<a.length-1;c++){var e=a[c];touches[e.identifier].left=!0}touches.length=a.length;break;case "end":for(c=0;c<a.length;c++)e=a[c],touches[e.identifier].left=!1;break;case "move":for(c=0;c<a.length;c++)e=a[c],touches[e.identifier].left=!0,touches[e.identifier].x=e.clientX-canvas.offsetLeft,touches[e.identifier].y=e.clientY-canvas.offsetTop}else for(c=globalSpeedY=globalSpeedX=0;c<touches.length;c++)if(e=
touches[c],e.reallywheel=e.wheel,e.wheel=0,e.speedx=e.x-e.lastx,e.speedy=e.y-e.lasty,globalSpeedX+=e.speedx,globalSpeedY+=e.speedy,e.lastX=e.x,e.lastY=e.y,e.left||e.right||e.middle)anyMousePress=!0}function MOUSEAXIS(a){if(0<=currentMouse&&currentMouse<touches.length){var b=touches[currentMouse];switch(a){case 0:return b.speedx;case 1:return b.speedy;case 2:return b.reallywheel;case 3:return b.left?1:0;case 4:return b.right?1:0;case 5:return b.middle?1:0}}}
function SETACTIVEMOUSE(a){currentMouse=a;(0>a||a>=touches.length)&&throwError("Invalid mouse index '"+a+"' max: '"+touches.length+"'")}function GETMOUSECOUNT(){return touches.length}function MOUSESTATE(a,b,c,e){if(0<=currentMouse&&currentMouse<touches.length){var f=touches[currentMouse];a[0]=f.x;b[0]=f.y;c[0]=f.left?1:0;e[0]=f.right?1:0}}function SYSTEMPOINTER(a){canvas.style.cursor=a?"":"none"}function KEY(a){a=glb2jsKeyCode(a);return keyInput[a]?1:0}
function glb2jsKeyCode(a){switch(a){case 14:return 8;case 15:return 9;case 28:return 13;case 42:return 16;case 29:case 157:return 17;case 56:case 29:case 184:return 18;case 197:return 19;case 58:return 20;case 1:return 27;case 201:return 33;case 57:return 32;case 209:return 34;case 207:return 35;case 178:return 36;case 203:return 37;case 200:return 38;case 205:return 39;case 208:return 40;case 183:return 44;case 210:return 45;case 211:return 46;case 11:return 48;case 2:return 49;case 3:return 50;
case 4:return 51;case 5:return 52;case 6:return 53;case 7:return 54;case 8:return 55;case 9:return 56;case 10:return 57;case 30:return 65;case 48:return 66;case 46:return 67;case 32:return 68;case 18:return 69;case 33:return 70;case 34:return 71;case 35:return 72;case 23:return 73;case 36:return 74;case 37:return 75;case 38:return 76;case 50:return 77;case 49:return 78;case 24:return 79;case 25:return 80;case 16:return 81;case 19:return 82;case 31:return 83;case 20:return 84;case 22:return 85;case 47:return 86;
case 17:return 87;case 45:return 88;case 44:return 89;case 21:return 90;case 219:return 91;case 220:return 92;case 82:return 96;case 79:return 97;case 80:return 98;case 81:return 99;case 75:return 100;case 76:return 101;case 77:return 102;case 71:return 103;case 72:return 104;case 73:return 105;case 55:return 106;case 78:return 107;case 74:return 109;case 83:return 110;case 181:return 111;case 59:return 112;case 60:return 113;case 61:return 114;case 62:return 115;case 63:return 116;case 64:return 117;
case 65:return 118;case 66:return 119;case 67:return 120;case 68:return 121;case 87:return 122;case 88:return 123;case 69:return 144;case KEY_SCROLLLOCK=145:return 70}}function INKEY_Str(){return""}function ANYKEY(){return anyKeyPress?1:0}function ANYMOUSE(){return anyMousePress?1:0}function Sprite(a,b){this.img=a;this.num=b;this.data=null;this.loaded=!1;this.frames=this.tint=null;this.frameHeight=this.frameWidth=-1}
function getSprite(a){if(sprites[a])return sprites[a].loaded||throwError("Image not yet loaded '"+a+"'"),sprites[a];throwError("Image not available '"+a+"'")}
function LOADSPRITE(a,b){var c=new Image,e=new Sprite(c,b);c.onerror=function(){sprites[b]&&(waitload--,sprites[b]=null,""!=a&&"0"!=a&&throwError("Image '"+b+"' '"+a+"' not found!"))};c.onload=function(){if(!e.loaded){waitload--;e.loaded=!0;updateFrames(b);try{if(transCol){var a=c.width,g=c.height,h=document.createElement("canvas");h.width=a;h.height=g;var k=new Screen(h,-42);k.context.drawImage(c,0,0);for(var j=k.context.getImageData(0,0,a,g),l=0;l<g;l++){outpos=inpos=4*l*a;for(var m=0;m<a;m++){var p=
j.data[inpos++],r=j.data[inpos++],n=j.data[inpos++],q=j.data[inpos++];RGB(p,r,n)==transCol&&(q=0);j.data[outpos++]=p;j.data[outpos++]=r;j.data[outpos++]=n;j.data[outpos++]=q}}k.context.putImageData(j,0,0);e.img=h}}catch(s){domExceptionError(s)}}};c.src=fileSystem.getCurrentDir()+a;register(e);waitload++}
function SETSPRITEANIM(a,b,c){var e=sprites[a];e||throwError("Cannot SETSPRITEANIM to unloaded sprite '"+a+"'");e.frames=null;b&&c?(e.frameWidth=b,e.frameHeight=c):(e.frameWidth=-1,e.frameHeight=-1);e.loaded&&updateFrames(a)}
function updateFrames(a){a=getSprite(a);if(-1!=a.frameWidth&&-1!=a.frameHeight){a.frameWidth=MAX(MIN(a.frameWidth,a.img.width),0);a.frameHeight=MAX(MIN(a.frameHeight,a.img.height),0);a.frames=[];for(var b=0;b<a.img.height;b+=a.frameHeight)for(var c=0;c<a.img.width;c+=a.frameWidth)a.frames.push({posx:c,posy:b})}}function LOADANIM(a,b,c,e){LOADSPRITE(a,b,c,e);SETSPRITEANIM(b,c,e)}function LOADFONT(){}function MEM2SPRITE(){throwError("TODO: mem2sprite")}
function SPRITE2MEM(a,b){var c=a.deval instanceof Array,e=getSprite(b);c?DIM(a,[e.img.width*e.img.height],[0]):DIM(a,[e.img.width*e.img.height],0);var f=e.img.width,g=e.img.height,h=document.createElement("canvas");h.width=f;h.height=g;h=new Screen(h,-42);h.context.drawImage(e.img,0,0);try{for(var k=h.context.getImageData(0,0,f,g),e=0;e<g;e++)for(var h=4*e*f,j=0;j<f;j++){var l=k.data[h++],m=k.data[h++],p=k.data[h++],r=k.data[h++],n=bOR(RGB(l,m,p),ASL(r,24));c&&(n=[n]);a.arrAccess(j+e*f).values[tmpPositionCache]=
n}}catch(q){return 0}return 1}function LOADSPRITEMEM(){throwError("TODO: loadspritemem")}var inPoly=!1,num,mode,polyStack=[],tmpPolyStack=Array(3);
function ENDPOLY(){inPoly||throwError("ENDPOLY has to be in STARTPOLY - ENDPOLY ");if(0<polyStack.length){if(4==polyStack.length)POLYNEWSTRIP();else if(1==mode){0!=polyStack.length%3&&throwError("Polyvector cannot draw non power of 3 triangles");for(var a=getSprite(num),b=0;b<polyStack.length;b+=3)tmpPolyStack[0]=polyStack[b],tmpPolyStack[1]=polyStack[b+1],tmpPolyStack[2]=polyStack[b+2],drawPolygon(!1,simpletris,tmpPolyStack,a);context.restore()}else throwError("Missing ENDPOLY function.");polyStack.length=
0}inPoly=!1}var simpletris=[[0,1,2]],tris2=[[0,1,2],[2,3,1]],tris1=[[0,1,2],[2,3,0]];
function POLYNEWSTRIP(){inPoly||throwError("POLYNEWSTRIP has to be in STARTPOLY - ENDPOLY ");if(-1==num){context.fillStyle=formatColor(polyStack[0].col);context.beginPath();context.moveTo(0,0);for(var a=0;a<polyStack.length;a++)context.lineTo(~~(polyStack[a].x+0.5),~~(polyStack[a].y+0.5));context.closePath();context.fill();polyStack.length=0}else{2==mode?a=tris2:1==mode?a=tris1:0==mode?a=tris1:throwError("Invalid drawing mode!");var b=getSprite(num),c;c=polyStack[0].col!=whiteRGB&&polyStack[1].col!=
whiteRGB&&polyStack[2].col!=whiteRGB&&polyStack[2].col!=whiteRGB?!0:!1;var e=context.globalAlpha,f=context.globalCompositeOperation;drawPolygon(c,a,polyStack,b)}c&&(context.globalAlpha=e,context.globalCompositeOperation=f);polyStack.length=0}
function drawPolygon(a,b,c,e){for(var f=0;f<b.length;f++){var g=b[f],h=c[g[0]].x,k=c[g[1]].x,j=c[g[2]].x,l=c[g[0]].y,m=c[g[1]].y,p=c[g[2]].y,r=c[g[0]].u,n=c[g[1]].u,q=c[g[2]].u,s=c[g[0]].v,t=c[g[1]].v,g=c[g[2]].v;context.save();context.beginPath();context.moveTo(h,l);context.lineTo(k,m);context.lineTo(j,p);context.closePath();context.clip();var u=r*t+s*q+n*g-t*q-s*n-r*g;context.transform((h*t+s*j+k*g-t*j-s*k-h*g)/u,(l*t+s*p+m*g-t*p-s*m-l*g)/u,(r*k+h*q+n*j-k*q-h*n-r*j)/u,(r*m+l*q+n*p-m*q-l*n-r*p)/
u,(r*t*j+s*k*q+h*n*g-h*t*q-s*n*j-r*k*g)/u,(r*t*p+s*m*q+l*n*g-l*t*q-s*n*p-r*m*g)/u);if(a){if(c[0].col==c[1].col&&c[1].col==c[2].col&&2<polyStacj.length&&c[2].col==c[3].col){if(!e.tint)try{e.tint=generateRGBKs(e.img)}catch(v){domExceptionError(v)}if(e.tint&&(h=(c[f].col&16711680)/65536,k=(c[f].col&65280)/256,j=c[f].col&255,context.globalAlpha=1,context.globalCompositeOperation="copy",context.drawImage(e.tint[3],0,0),context.globalCompositeOperation="lighter",0<h&&(context.globalAlpha=h/255,context.drawImage(e.tint[0],
0,0)),0<k&&(context.globalAlpha=k/255,context.drawImage(e.tint[1],0,0)),0<j))context.globalAlpha=j/255,context.drawImage(e.tint[2],0,0)}}else context.drawImage(e.img,0,0);context.restore()}}
function POLYVECTOR(a,b,c,e,f){inPoly||throwError("POLYVECTOR has to be in STARTPOLY - ENDPODRAWANIMLY ");polyStack[polyStack.length]?(polyStack[polyStack.length].x=a,polyStack[polyStack.length].y=b,polyStack[polyStack.length].u=c,polyStack[polyStack.length].v=e,polyStack[polyStack.length].col=f,polyStack.length++):polyStack.push({x:a,y:b,u:c,v:e,col:f})}function STARTPOLY(a,b){inPoly&&throwError("STARTPOLY has not to be in STARTPOLY - ENDPOLY ");inPoly=!0;polyStack.length=0;num=a;mode=b}
function GENSPRITE(){for(var a=0;a<sprites.length;a++)if(!sprites[a])return a;return sprites.length}function DRAWSPRITE(a,b,c){a=getSprite(a);context.drawImage(a.img,~~(b+0.5),~~(c+0.5))}function ROTOSPRITE(a,b,c,e){0==e%360?DRAWSPRITE(a,b,c):(context.save(),context.setRotation(e*Math.PI/180),DRAWSPRITE(a,b,c),context.restore())}function ZOOMSPRITE(a,b,c,e,f){1==e&&1==f?DRAWSPRITE(a,b,c):0!=e&&0!=f&&(context.save(),context.translate(b,c),context.scale(e,f),DRAWSPRITE(a,0,0),context.restore())}
function STRETCHSPRITE(a,b,c,e,f){var g=getSprite(a);0!=e&&0!=f&&(context.save(),e/=g.img.width,f/=g.img.height,context.translate(b,c),context.scale(e,f),DRAWSPRITE(a,0,0),context.restore())}function ROTOZOOMSPRITE(a,b,c,e,f){context.save();context.translate(b,c);context.scale(f,f);ROTOSPRITE(a,0,0,e);context.restore()}
function DRAWANIM(a,b,c,e){a=getSprite(a);null==a.frames&&throwError("DRAWANIM can only draw an animation!");b%=a.frames.length;0>b&&throwError("Invalid frame '"+b+"'");context.drawImage(a.img,~~(a.frames[b].posx+0.5),~~(a.frames[b].posy+0.5),a.frameWidth,a.frameHeight,CAST2INT(c),CAST2INT(e),a.frameWidth,a.frameHeight)}function ROTOZOOMANIM(a,b,c,e,f,g){context.save();context.translate(c,e);context.scale(g,g);ROTOANIM(a,b,0,0,f);context.restore()}
function ROTOANIM(a,b,c,e,f){0==f%360?DRAWANIM(a,b,c,e):(context.save(),context.setRotation(f*Math.PI/180),DRAWANIM(a,b,c,e),context.restore())}function ZOOMANIM(a,b,c,e,f,g){1==f&&1==g?DRAWANIM(a,b,c,e):0!=f&&0!=g&&(context.save(),context.translate(c,e),context.scale(f,g),DRAWANIM(a,b,0,0),context.restore())}
function STRETCHANIM(a,b,c,e,f,g){var h=getSprite(a);0!=f&&0!=g&&(context.save(),f/=h.img.frameWidth,g/=h.img.frameHeight,context.translate(c,e),context.scale(f,g),DRAWANIM(a,b,0,0),context.restore())}function GRABSPRITE(a,b,c,e,f){(1>e||1>f)&&throwError("Invalid width/height!");try{var g=context.getImageData(b,c,e,f),h=document.createElement("canvas");h.width=e;h.height=f;h.getContext("2d").putImageData(g,0,0);var k=new Sprite(h,a);k.loaded=!0;register(k)}catch(j){domExceptionError(j)}}
function SPRCOLL(a,b,c,e,f,g){a=getSprite(a);e=getSprite(e);if(!a.data||!e.data){var h=function(a){try{var b=document.createElement("canvas");b.width=a.img.width;b.height=a.img.height;var c=b.getContext("2d");c.drawImage(a.img,0,0);a.data=c.getImageData(0,0,b.width,b.height)}catch(e){domExceptionError(e)}};null==a.data&&h(a);null==e.data&&h(e)}return isPixelCollision(a.data,b,c,e.data,f,g)?1:0}function ANIMCOLL(){throwError("TODO: animcoll")}
function isPixelCollision(a,b,c,e,f,g){var b=Math.round(b),c=Math.round(c),f=Math.round(f),g=Math.round(g),h=a.width,k=a.height,j=e.width,l=e.height,m=Math.max(b,f),p=Math.max(c,g),r=Math.min(b+h,f+j),k=Math.min(c+k,g+l);if(m>=r||p>=k)return!1;var l=r-m,n=k-p,a=a.data,e=e.data;if(4>l&&4>n)for(n=m;n<r;n++)for(var q=p;q<k;q++){if(0!==a[4*(n-b+(q-c)*h)+3]&&0!==e[4*(n-f+(q-g)*j)+3])return!0}else for(var l=l/3,s=n/3,l=~~l===l?l:l+1|0,s=~~s===s?s:s+1|0,t=0;t<s;t++)for(var u=0;u<l;u++)for(q=p+t;q<k;q+=s)for(n=
m+u;n<r;n+=l)if(0!==a[4*(n-b+(q-c)*h)+3]&&0!==e[4*(n-f+(q-g)*j)+3])return!0;return!1}
function generateRGBKs(a){var b=a.width,c=a.height,e=[],f=document.createElement("canvas");f.width=b;f.height=c;var g=f.getContext("2d");g.drawImage(a,0,0);for(var h=g.getImageData(0,0,b,c).data,k=0;4>k;k++){f=document.createElement("canvas");f.width=b;f.height=c;g=f.getContext("2d");g.drawImage(a,0,0);for(var j=g.getImageData(0,0,b,c),l=j.data,m=0,p=h.length;m<p;m+=4)l[m]=0===k?h[m]:0,l[m+1]=1===k?h[m+1]:0,l[m+2]=2===k?h[m+2]:0,l[m+3]=h[m+3];g.putImageData(j,0,0);g=new Image;g.src=f.toDataURL();
e.push(g)}return e}function BOXCOLL(a,b,c,e,f,g,h,k){return a<=f+h&&b<=g+k&&a+c>=f&&b+e>=g?1:0}function Screen(a,b,c){this.canvas=a;this.context=a.getContext("2d");this.realwidth=this.canvas.width;this.realheight=this.canvas.height;this.realx=this.canvas.offsetLeft;this.realy=this.canvas.offsetRight;this.num=b+2;this.spr=c;null==this.context&&throwError("Given buffer does not support '2d'")}
function CREATESCREEN(a,b,c,e){var f=document.createElement("canvas");f.width=c;f.height=e;register(new Screen(f,a,b));register(new Sprite(f,b))}function USESCREEN(a){var b=curScreen;b&&b.spr&&(getSprite(b.spr).data=null,getSprite(b.spr).tint=null);(curScreen=screens[a+2])?(context=curScreen.context,canvas=curScreen.canvas):curScreen=b}function BLENDSCREEN(){throwError("TODO: blendscreen")}
function CLEARSCREEN(a){context.save();context.fillStyle=formatColor(a);context.fillRect(0,0,canvas.width,canvas.height);clrColor=a;context.restore()}function BLACKSCREEN(){CLEARSCREEN(RGB(0,0,0))}function USEASBMP(){background=backbuffer.canvas;var a=document.createElement("canvas");a.width=canvasWidth;a.height=canvasHeight;backbuffer=new Screen(a,-1);register(backbuffer);USESCREEN(-1)}
function LOADBMP(a){var b=new Image;b.onload=function(){background=b};b.onerror=function(){throwError("BMP '"+a+"' not found!")};b.src=fileSystem.getCurrentDir()+a}var debugMode=!1;window.main=function(){var a=func_proto,b=new type4_Tfoo,c=[func_proto];0==CAST2FLOAT(a)&&STDOUT("has no pointer\n");func2_f1(1);a=func2_f2;a(2);func4_call(a);b.attr3_moo_ref[0]=func2_f1;b.attr3_moo_ref[0](4);c=b.attr3_moo_ref;c[0](5)};window.func2_f1=function(a){a=unref(a);STDOUT("f1: "+CAST2STRING(a)+"\n");return 0};
window.func2_f2=function(a){a=unref(a);STDOUT("f2: "+CAST2STRING(a)+"\n");return 0};window.func4_call=function(a){a=unref(a);a(3);return 0};window.method13_type7_TObject_12_ToString_Str=function(a){unref(a);return"Object"};window.method13_type7_TObject_6_Equals=function(a,b){a=unref(a);b=unref(b);return a==b?1:tryClone(0)};window.method13_type7_TObject_10_ToHashCode=function(a){unref(a);return 0};window.func_proto=function(){return function(){throwError("NullPrototypeException")}};
var vtbl_type4_Tfoo={ToString_Str:method13_type7_TObject_12_ToString_Str,Equals:method13_type7_TObject_6_Equals,ToHashCode:method13_type7_TObject_10_ToHashCode};window.type4_Tfoo=function(){this.attr3_moo_ref=[func_proto];this.vtbl=vtbl_type4_Tfoo;return this};window.type4_Tfoo.prototype.clone=function(){var a=new type4_Tfoo;a.attr3_moo_ref=tryClone(this.attr3_moo_ref);a.vtbl=this.vtbl;return a};type4_Tfoo.prototype.ToString_Str=function(){return this.vtbl.ToString_Str(this)};
type4_Tfoo.prototype.Equals=function(a){return this.vtbl.Equals(a,this)};type4_Tfoo.prototype.ToHashCode=function(){return this.vtbl.ToHashCode(this)};var vtbl_type7_TObject={ToString_Str:method13_type7_TObject_12_ToString_Str,Equals:method13_type7_TObject_6_Equals,ToHashCode:method13_type7_TObject_10_ToHashCode};window.type7_TObject=function(){this.vtbl=vtbl_type7_TObject;return this};window.type7_TObject.prototype.clone=function(){var a=new type7_TObject;a.vtbl=this.vtbl;return a};
type7_TObject.prototype.ToString_Str=function(){return this.vtbl.ToString_Str(this)};type7_TObject.prototype.Equals=function(a){return this.vtbl.Equals(a,this)};type7_TObject.prototype.ToHashCode=function(){return this.vtbl.ToHashCode(this)};window.initStatics=function(){};for(var __init=0;__init<preInitFuncs.length;__init++)preInitFuncs[__init]();
