var staticFileSystem,fileSystem,initFS=function(){staticFileSystem=new VirtualFileSystem;fileSystem=new VirtualFileSystem(localStorage.getItem("filesystem"));staticFileSystem.createDir("/media");fileSystem.createDir("/media");staticFileSystem.createFile("/keys.ini",[91,114,111,111,116,93,13,10,49,110,97,109,101,61,83,116,97,114,116,13,10,49,116,121,112,101,61,98,117,116,116,111,110,13,10,49,118,97,108,117,101,61,49,13,10,50,110,97,109,101,61,69,120,105,116,13,10,50,116,121,112,101,61,98,117,116,116,
111,110,13,10,50,118,97,108,117,101,61,45,49,13,10,51,110,97,109,101,61,79,112,116,105,111,110,115,13,10,51,116,121,112,101,61,100,105,114,13,10,51,118,97,108,117,101,61,111,112,116,105,111,110,115,13,10,91,111,112,116,105,111,110,115,93,13,10,49,110,97,109,101,61,73,110,112,117,116,13,10,49,116,121,112,101,61,100,105,114,13,10,49,118,97,108,117,101,61,107,101,121,99,111,110,102,105,103,13,10,50,110,97,109,101,61,77,117,115,105,99,13,10,50,116,121,112,101,61,116,111,103,103,108,101,58,32,111,102,
102,44,32,111,110,13,10,50,118,97,108,117,101,61,49,13,10,51,110,97,109,101,61,86,111,108,117,109,101,13,10,51,116,121,112,101,61,116,111,103,103,108,101,58,32,50,53,44,32,53,48,44,32,55,53,44,32,49,48,48,13,10,51,118,97,108,117,101,61,50,13,10,91,107,101,121,99,111,110,102,105,103,93,13,10,49,110,97,109,101,61,80,108,97,121,101,114,32,49,13,10,49,116,121,112,101,61,100,105,114,13,10,49,118,97,108,117,101,61,107,101,121,99,111,110,102,105,103,49,13,10,50,110,97,109,101,61,80,108,97,121,101,114,32,
50,13,10,50,116,121,112,101,61,100,105,114,13,10,50,118,97,108,117,101,61,107,101,121,99,111,110,102,105,103,50,13,10,51,110,97,109,101,61,80,108,97,121,101,114,32,51,13,10,51,116,121,112,101,61,100,105,114,13,10,51,118,97,108,117,101,61,107,101,121,99,111,110,102,105,103,51,13,10,52,110,97,109,101,61,80,108,97,121,101,114,32,52,13,10,52,116,121,112,101,61,100,105,114,13,10,52,118,97,108,117,101,61,107,101,121,99,111,110,102,105,103,52,13,10,91,107,101,121,99,111,110,102,105,103,49,93,13,10,49,110,
97,109,101,61,85,112,13,10,49,116,121,112,101,61,107,101,121,13,10,49,118,97,108,117,101,61,75,50,48,48,13,10,50,110,97,109,101,61,68,111,119,110,13,10,50,116,121,112,101,61,107,101,121,13,10,50,118,97,108,117,101,61,75,50,48,56,13,10,51,110,97,109,101,61,76,101,102,116,13,10,51,116,121,112,101,61,107,101,121,13,10,51,118,97,108,117,101,61,75,50,48,51,13,10,52,110,97,109,101,61,82,105,103,104,116,13,10,52,116,121,112,101,61,107,101,121,13,10,52,118,97,108,117,101,61,75,50,48,53,13,10,53,110,97,109,
101,61,66,117,116,116,111,110,13,10,53,116,121,112,101,61,107,101,121,13,10,53,118,97,108,117,101,61,75,50,56,13,10,91,107,101,121,99,111,110,102,105,103,50,93,13,10,49,110,97,109,101,61,85,112,13,10,49,116,121,112,101,61,107,101,121,13,10,49,118,97,108,117,101,61,74,48,45,50,13,10,50,110,97,109,101,61,68,111,119,110,13,10,50,116,121,112,101,61,107,101,121,13,10,50,118,97,108,117,101,61,74,48,45,51,13,10,51,110,97,109,101,61,76,101,102,116,13,10,51,116,121,112,101,61,107,101,121,13,10,51,118,97,108,
117,101,61,74,48,45,48,13,10,52,110,97,109,101,61,82,105,103,104,116,13,10,52,116,121,112,101,61,107,101,121,13,10,52,118,97,108,117,101,61,74,48,45,49,13,10,53,110,97,109,101,61,66,117,116,116,111,110,13,10,53,116,121,112,101,61,107,101,121,13,10,53,118,97,108,117,101,61,74,48,45,49,54,13,10,91,107,101,121,99,111,110,102,105,103,51,93,13,10,49,110,97,109,101,61,85,112,13,10,49,116,121,112,101,61,107,101,121,13,10,49,118,97,108,117,101,61,75,55,50,13,10,50,110,97,109,101,61,68,111,119,110,13,10,50,
116,121,112,101,61,107,101,121,13,10,50,118,97,108,117,101,61,75,56,48,13,10,51,110,97,109,101,61,76,101,102,116,13,10,51,116,121,112,101,61,107,101,121,13,10,51,118,97,108,117,101,61,75,55,53,13,10,52,110,97,109,101,61,82,105,103,104,116,13,10,52,116,121,112,101,61,107,101,121,13,10,52,118,97,108,117,101,61,75,55,55,13,10,53,110,97,109,101,61,66,117,116,116,111,110,13,10,53,116,121,112,101,61,107,101,121,13,10,53,118,97,108,117,101,61,75,56,50,13,10,91,107,101,121,99,111,110,102,105,103,52,93,13,
10,49,110,97,109,101,61,85,112,13,10,49,116,121,112,101,61,107,101,121,13,10,49,118,97,108,117,101,61,75,49,55,13,10,50,110,97,109,101,61,68,111,119,110,13,10,50,116,121,112,101,61,107,101,121,13,10,50,118,97,108,117,101,61,75,51,49,13,10,51,110,97,109,101,61,76,101,102,116,13,10,51,116,121,112,101,61,107,101,121,13,10,51,118,97,108,117,101,61,75,51,48,13,10,52,110,97,109,101,61,82,105,103,104,116,13,10,52,116,121,112,101,61,107,101,121,13,10,52,118,97,108,117,101,61,75,51,50,13,10,53,110,97,109,
101,61,66,117,116,116,111,110,13,10,53,116,121,112,101,61,107,101,121,13,10,53,118,97,108,117,101,61,75,49,54,13,10]);initFS=null},viewMode="graphics",compileTime="?=>?:=B:=A-?>G@BG?>",userDefVersion="===;==>",hostId="?F=E>CqB",uniqueId=(new Date).getTime()+""+1E7*Math.random(),startTime=(new Date).getTime(),debugMode=!1,global6_g_ctrl=new GLBArray,global12_menu_dir_Str="",global8_menu_pos=0,global9_menu_fade=0,global12_menu_keymode=0,global9_menu_back=0,global14_menu_nullstate=new type12_KEYDEF_STATE,
global4_item=0,global3_pos=new GLBArray;
function main(){var a=0;DIM(unref(global6_g_ctrl),[4],new type7_CONTROL);for(func8_MenuInit("keys.ini");!(global4_item=func8_MenuShow());)SHOWSCREEN();CAST2FLOAT(global4_item==CAST2FLOAT(-1)?1:0)&&END();DIM(unref(global3_pos),[4,2],0);INIOPEN("keys.ini");for(a=0;forCheck(a,3,1);a+=1)global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr6_up_Str=INIGET_Str("keyconfig"+CAST2STRING(a+1),"1value","NO_DATA"),global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr8_down_Str=INIGET_Str("keyconfig"+
CAST2STRING(a+1),"2value","NO_DATA"),global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr7_lft_Str=INIGET_Str("keyconfig"+CAST2STRING(a+1),"3value","NO_DATA"),global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr8_rght_Str=INIGET_Str("keyconfig"+CAST2STRING(a+1),"4value","NO_DATA"),global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr10_button_Str=INIGET_Str("keyconfig"+CAST2STRING(a+1),"5value","NO_DATA"),global3_pos.arrAccess(a,0).values[tmpPositionCache]=100,global3_pos.arrAccess(a,
1).values[tmpPositionCache]=20+20*a;for(;;){PRINT("Music: "+INIGET_Str("options","2value","NO_DATA"),0,0,0);PRINT("volume:"+INIGET_Str("options","3value","NO_DATA"),0,20,0);for(a=0;forCheck(a,3,1);a+=1)global3_pos.arrAccess(a,0).values[tmpPositionCache]+=CAST2INT(func10_keydef_key(global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr8_rght_Str)-func10_keydef_key(global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr7_lft_Str)),global3_pos.arrAccess(a,1).values[tmpPositionCache]+=CAST2INT(func10_keydef_key(global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr8_down_Str)-
func10_keydef_key(global6_g_ctrl.arrAccess(a).values[tmpPositionCache].attr6_up_Str)),PRINT("Player "+CAST2STRING(a),unref(global3_pos.arrAccess(a,0).values[tmpPositionCache]),unref(global3_pos.arrAccess(a,1).values[tmpPositionCache]),0);SHOWSCREEN()}}
function func15_keydef_getstate(a){for(var a=unref(a),b=0,c=0,e=0,b=1;forCheck(b,255,1);b+=1)a.attr4_keys.arrAccess(b).values[tmpPositionCache]=CAST2FLOAT(KEY(unref(CAST2INT(b))));e=CAST2FLOAT(GETNUMJOYSTICKS());DIM(unref(a.attr4_joys),[e,48],0);for(b=0;forCheck(b,e-1,1);b+=1)for(c=0;forCheck(c,47,1);c+=1)a.attr4_joys.arrAccess(b,c).values[tmpPositionCache]=func15_keydef_joystate(b,c,0.4);return 0}
function func15_keydef_joystate(a,b,c){var a=unref(a),b=unref(b),c=unref(c),e=0,e=0,e=b;if(0==e){if(e=GETJOYX(unref(CAST2INT(a))),CAST2FLOAT(e<-c?1:0))return tryClone(ABS(unref(e)))}else if(1==e){if(e=GETJOYX(unref(CAST2INT(a))),CAST2FLOAT(e>c?1:0))return tryClone(unref(e))}else if(2==e){if(e=GETJOYY(unref(CAST2INT(a))),CAST2FLOAT(e<-c?1:0))return tryClone(ABS(unref(e)))}else if(3==e){if(e=GETJOYY(unref(CAST2INT(a))),CAST2FLOAT(e>c?1:0))return tryClone(unref(e))}else if(4==e){if(e=GETJOYZ(unref(CAST2INT(a))),
CAST2FLOAT(e<-c?1:0))return tryClone(ABS(unref(e)))}else if(5==e){if(e=GETJOYZ(unref(CAST2INT(a))),CAST2FLOAT(e>c?1:0))return tryClone(unref(e))}else if(6==e){if(e=GETJOYRX(unref(CAST2INT(a))),CAST2FLOAT(e<-c?1:0))return tryClone(ABS(unref(e)))}else if(7==e){if(e=GETJOYRX(unref(CAST2INT(a))),CAST2FLOAT(e>c?1:0))return tryClone(unref(e))}else if(8==e){if(e=GETJOYRY(unref(CAST2INT(a))),CAST2FLOAT(e<-c?1:0))return tryClone(ABS(unref(e)))}else if(9==e){if(e=GETJOYRY(unref(CAST2INT(a))),CAST2FLOAT(e>c?
1:0))return tryClone(unref(e))}else if(10==e){if(e=GETJOYRZ(unref(CAST2INT(a))),CAST2FLOAT(e<-c?1:0))return tryClone(ABS(unref(e)))}else if(11==e){if(e=GETJOYRZ(unref(CAST2INT(a))),CAST2FLOAT(e>c?1:0))return tryClone(unref(e))}else if(12==e){if(e=GETDIGIX(unref(CAST2INT(a))),CAST2FLOAT(0<e?1:0))return tryClone(ABS(unref(e)))}else if(13==e){if(e=GETDIGIX(unref(CAST2INT(a))),CAST2FLOAT(0<e?1:0))return tryClone(unref(e))}else if(14==e){if(e=GETDIGIY(unref(CAST2INT(a))),CAST2FLOAT(0<e?1:0))return tryClone(ABS(unref(e)))}else if(15==
e){if(e=GETDIGIY(unref(CAST2INT(a))),CAST2FLOAT(0<e?1:0))return tryClone(unref(e))}else if(e=GETJOYBUTTON(unref(CAST2INT(a)),CAST2INT(b-16)))return tryClone(1);return tryClone(0)}
function func10_keydef_key(a){a=unref(a);new GLBArray;var b="",c=b=0,b=MID_Str(unref(a),0,1);if(CAST2FLOAT("K"==b?1:0))return a=MID_Str(unref(a),1,256),tryClone(CAST2FLOAT(KEY(unref(CAST2INT(a)))));if(CAST2FLOAT("J"==b?1:0))if(b=CAST2FLOAT(MID_Str(unref(a),1,1)),c=CAST2FLOAT(INSTR(unref(a),"-",0)),CAST2FLOAT(0<=c?1:0))return tryClone(func15_keydef_joystate(b,CAST2FLOAT(MID_Str(unref(a),CAST2INT(c+1),128)),0));return tryClone(0)}
function func24_keydef_get_nice_name_Str(a){var a=unref(a),b="",c=new GLBArray,e="",b="*NONE*",e=MID_Str(unref(a),0,1);if(CAST2FLOAT("K"==e?1:0)){a=MID_Str(unref(a),1,256);if(CAST2FLOAT(0==LEN(a)?1:0))return tryClone(unref(b));func15_keydef_keynames(c);return tryClone(unref(c.arrAccess(a).values[tmpPositionCache]))}return CAST2FLOAT("J"==e?1:0)?CAST2FLOAT(2!=SPLITSTR(unref(a),unref(c),"-",1)?1:0)?tryClone(CAST2STRING(0)):tryClone("J"+CAST2STRING(INTEGER(CAST2FLOAT(MID_Str(unref(c.arrAccess(0).values[tmpPositionCache]),
1,16)+CAST2STRING(1))))+","+func18_keydef_joyname_Str(CAST2FLOAT(c.arrAccess(1).values[tmpPositionCache]))):tryClone(unref(b))}
function func19_keydef_get_name_Str(a,b){var a=unref(a),b=unref(b),c=0,e=0;new GLBArray;for(c=0;forCheck(c,255,1);c+=1)if(CAST2FLOAT(a.attr4_keys.arrAccess(c).values[tmpPositionCache]&&CAST2FLOAT(0==b.attr4_keys.arrAccess(c).values[tmpPositionCache]?1:0)?1:0))return tryClone("K"+CAST2STRING(c));for(c=0;forCheck(c,CAST2FLOAT(MIN(unref(CAST2FLOAT(BOUNDS(a.attr4_joys,0))),unref(CAST2FLOAT(BOUNDS(b.attr4_joys,0))))-1),1);c+=1)for(e=0;forCheck(e,47,1);e+=1)if(CAST2FLOAT(a.attr4_joys.arrAccess(c,e).values[tmpPositionCache]&&
CAST2FLOAT(0==b.attr4_joys.arrAccess(c,e).values[tmpPositionCache]?1:0)?1:0))return tryClone("J"+CAST2STRING(c)+"-"+CAST2STRING(e));return""}function func18_keydef_joyname_Str(a){var a=unref(a),b=0,b=a;return 0==b?"NEG_X":1==b?"POS_X":2==b?"NEG_Y":3==b?"POS_Y":4==b?"NEG_Z":5==b?"POS_Z":6==b?"NEG_RX":7==b?"POS_RX":8==b?"NEG_RY":9==b?"POS_RY":10==b?"NEG_RZ":11==b?"POS_RZ":12==b?"NEG_POVX":13==b?"POS_POVX":14==b?"NEG_POVY":15==b?"POS_POVY":tryClone("BUT_"+CAST2STRING(a-15))}
function func15_keydef_keynames(a){a=unref(a);DIM(unref(a),[256],"");a.arrAccess(1).values[tmpPositionCache]="ESC";a.arrAccess(2).values[tmpPositionCache]="1";a.arrAccess(3).values[tmpPositionCache]="2";a.arrAccess(4).values[tmpPositionCache]="3";a.arrAccess(5).values[tmpPositionCache]="4";a.arrAccess(6).values[tmpPositionCache]="5";a.arrAccess(7).values[tmpPositionCache]="6";a.arrAccess(8).values[tmpPositionCache]="7";a.arrAccess(9).values[tmpPositionCache]="8";a.arrAccess(10).values[tmpPositionCache]=
"9";a.arrAccess(11).values[tmpPositionCache]="0";a.arrAccess(12).values[tmpPositionCache]="MINUS";a.arrAccess(13).values[tmpPositionCache]="EQUALS";a.arrAccess(14).values[tmpPositionCache]="BACK";a.arrAccess(15).values[tmpPositionCache]="TAB";a.arrAccess(16).values[tmpPositionCache]="Q";a.arrAccess(17).values[tmpPositionCache]="W";a.arrAccess(18).values[tmpPositionCache]="E";a.arrAccess(19).values[tmpPositionCache]="R";a.arrAccess(20).values[tmpPositionCache]="T";a.arrAccess(21).values[tmpPositionCache]=
"Y";a.arrAccess(22).values[tmpPositionCache]="U";a.arrAccess(23).values[tmpPositionCache]="I";a.arrAccess(24).values[tmpPositionCache]="O";a.arrAccess(25).values[tmpPositionCache]="P";a.arrAccess(26).values[tmpPositionCache]="LBRACKET";a.arrAccess(27).values[tmpPositionCache]="RBRACKET";a.arrAccess(28).values[tmpPositionCache]="RETURN";a.arrAccess(29).values[tmpPositionCache]="LCONTROL";a.arrAccess(30).values[tmpPositionCache]="A";a.arrAccess(31).values[tmpPositionCache]="S";a.arrAccess(32).values[tmpPositionCache]=
"D";a.arrAccess(33).values[tmpPositionCache]="F";a.arrAccess(34).values[tmpPositionCache]="G";a.arrAccess(35).values[tmpPositionCache]="H";a.arrAccess(36).values[tmpPositionCache]="J";a.arrAccess(37).values[tmpPositionCache]="K";a.arrAccess(38).values[tmpPositionCache]="L";a.arrAccess(39).values[tmpPositionCache]="SEMICOLON";a.arrAccess(40).values[tmpPositionCache]="APOSTROPHE";a.arrAccess(41).values[tmpPositionCache]="GRAVE";a.arrAccess(42).values[tmpPositionCache]="LSHIFT";a.arrAccess(43).values[tmpPositionCache]=
"BACKSLASH";a.arrAccess(44).values[tmpPositionCache]="Z";a.arrAccess(45).values[tmpPositionCache]="X";a.arrAccess(46).values[tmpPositionCache]="C";a.arrAccess(47).values[tmpPositionCache]="V";a.arrAccess(48).values[tmpPositionCache]="B";a.arrAccess(49).values[tmpPositionCache]="N";a.arrAccess(50).values[tmpPositionCache]="M";a.arrAccess(51).values[tmpPositionCache]="COMMA";a.arrAccess(52).values[tmpPositionCache]="PERIOD";a.arrAccess(53).values[tmpPositionCache]="SLASH";a.arrAccess(54).values[tmpPositionCache]=
"RSHIFT";a.arrAccess(55).values[tmpPositionCache]="MULTIPLY";a.arrAccess(56).values[tmpPositionCache]="LMENU";a.arrAccess(57).values[tmpPositionCache]="SPACE";a.arrAccess(58).values[tmpPositionCache]="CAPITAL";a.arrAccess(59).values[tmpPositionCache]="F1";a.arrAccess(60).values[tmpPositionCache]="F2";a.arrAccess(61).values[tmpPositionCache]="F3";a.arrAccess(62).values[tmpPositionCache]="F4";a.arrAccess(63).values[tmpPositionCache]="F5";a.arrAccess(64).values[tmpPositionCache]="F6";a.arrAccess(65).values[tmpPositionCache]=
"F7";a.arrAccess(66).values[tmpPositionCache]="F8";a.arrAccess(67).values[tmpPositionCache]="F9";a.arrAccess(68).values[tmpPositionCache]="F10";a.arrAccess(69).values[tmpPositionCache]="NUMLOCK";a.arrAccess(70).values[tmpPositionCache]="SCROLL";a.arrAccess(71).values[tmpPositionCache]="NUMPAD7";a.arrAccess(72).values[tmpPositionCache]="NUMPAD8";a.arrAccess(73).values[tmpPositionCache]="NUMPAD9";a.arrAccess(74).values[tmpPositionCache]="SUBTRACT";a.arrAccess(75).values[tmpPositionCache]="NUMPAD4";
a.arrAccess(76).values[tmpPositionCache]="NUMPAD5";a.arrAccess(77).values[tmpPositionCache]="NUMPAD6";a.arrAccess(78).values[tmpPositionCache]="ADD";a.arrAccess(79).values[tmpPositionCache]="NUMPAD1";a.arrAccess(80).values[tmpPositionCache]="NUMPAD2";a.arrAccess(81).values[tmpPositionCache]="NUMPAD3";a.arrAccess(82).values[tmpPositionCache]="NUMPAD0";a.arrAccess(83).values[tmpPositionCache]="DECIMAL";a.arrAccess(86).values[tmpPositionCache]="OEM_102";a.arrAccess(87).values[tmpPositionCache]="F11";
a.arrAccess(88).values[tmpPositionCache]="F12";a.arrAccess(100).values[tmpPositionCache]="F13";a.arrAccess(101).values[tmpPositionCache]="F14";a.arrAccess(102).values[tmpPositionCache]="F15";a.arrAccess(112).values[tmpPositionCache]="KANA";a.arrAccess(115).values[tmpPositionCache]="ABNT_C1";a.arrAccess(121).values[tmpPositionCache]="CONVERT";a.arrAccess(123).values[tmpPositionCache]="NOCONVERT";a.arrAccess(125).values[tmpPositionCache]="YEN";a.arrAccess(126).values[tmpPositionCache]="ABNT_C2";a.arrAccess(141).values[tmpPositionCache]=
"NUMPADEQUALS";a.arrAccess(144).values[tmpPositionCache]="PREVTRACK";a.arrAccess(145).values[tmpPositionCache]="AT";a.arrAccess(146).values[tmpPositionCache]="COLON";a.arrAccess(147).values[tmpPositionCache]="UNDERLINE";a.arrAccess(148).values[tmpPositionCache]="KANJI";a.arrAccess(149).values[tmpPositionCache]="STOP";a.arrAccess(150).values[tmpPositionCache]="AX";a.arrAccess(151).values[tmpPositionCache]="UNLABELED";a.arrAccess(153).values[tmpPositionCache]="NEXTTRACK";a.arrAccess(156).values[tmpPositionCache]=
"NUMPADENTER";a.arrAccess(157).values[tmpPositionCache]="RCONTROL";a.arrAccess(160).values[tmpPositionCache]="MUTE";a.arrAccess(161).values[tmpPositionCache]="CALCULATOR";a.arrAccess(162).values[tmpPositionCache]="PLAYPAUSE";a.arrAccess(164).values[tmpPositionCache]="MEDIASTOP";a.arrAccess(174).values[tmpPositionCache]="VOLUMEDOWN";a.arrAccess(176).values[tmpPositionCache]="VOLUMEUP";a.arrAccess(178).values[tmpPositionCache]="WEBHOME";a.arrAccess(179).values[tmpPositionCache]="NUMPADCOMMA";a.arrAccess(181).values[tmpPositionCache]=
"DIVIDE";a.arrAccess(183).values[tmpPositionCache]="SYSRQ";a.arrAccess(184).values[tmpPositionCache]="RMENU";a.arrAccess(197).values[tmpPositionCache]="PAUSE";a.arrAccess(199).values[tmpPositionCache]="HOME";a.arrAccess(200).values[tmpPositionCache]="UP";a.arrAccess(201).values[tmpPositionCache]="PRIOR";a.arrAccess(203).values[tmpPositionCache]="LEFT";a.arrAccess(205).values[tmpPositionCache]="RIGHT";a.arrAccess(207).values[tmpPositionCache]="END";a.arrAccess(208).values[tmpPositionCache]="DOWN";
a.arrAccess(209).values[tmpPositionCache]="NEXT";a.arrAccess(210).values[tmpPositionCache]="INSERT";a.arrAccess(211).values[tmpPositionCache]="DELETE";a.arrAccess(219).values[tmpPositionCache]="LWIN";a.arrAccess(220).values[tmpPositionCache]="RWIN";a.arrAccess(221).values[tmpPositionCache]="APPS";a.arrAccess(222).values[tmpPositionCache]="POWER";a.arrAccess(223).values[tmpPositionCache]="SLEEP";a.arrAccess(227).values[tmpPositionCache]="WAKE";a.arrAccess(229).values[tmpPositionCache]="WEBSEARCH";
a.arrAccess(230).values[tmpPositionCache]="WEBFAVORITES";a.arrAccess(231).values[tmpPositionCache]="WEBREFRESH";a.arrAccess(232).values[tmpPositionCache]="WEBSTOP";a.arrAccess(233).values[tmpPositionCache]="WEBFORWARD";a.arrAccess(234).values[tmpPositionCache]="WEBBACK";a.arrAccess(235).values[tmpPositionCache]="MYCOMPUTER";a.arrAccess(236).values[tmpPositionCache]="MAIL";a.arrAccess(237).values[tmpPositionCache]="MEDIASELECT";return 0}
function func8_MenuInit(a){a=unref(a);INIOPEN(unref(a));INIPUT("root","button","");global12_menu_dir_Str="root";global9_menu_fade=0.1;global12_menu_keymode=global9_menu_back=global8_menu_pos=0;func15_keydef_getstate(global14_menu_nullstate);return 0}function func12_MenuNavigate(){return CAST2FLOAT(KEY(200))?tryClone(1):CAST2FLOAT(KEY(203))?tryClone(2):CAST2FLOAT(KEY(208))?tryClone(3):CAST2FLOAT(KEY(205))?tryClone(4):CAST2FLOAT(KEY(28))?tryClone(5):tryClone(0)}
function func8_MenuShow(){for(var a=new type12_KEYDEF_STATE,b=0,c=0,e=0,c=0,e=e="",f=new GLBArray,g=new GLBArray,j=new GLBArray,k=new GLBArray,b=0;;){b+=1;e=INIGET_Str(unref(global12_menu_dir_Str),CAST2STRING(b)+"name","NO_DATA");if(CAST2FLOAT("NO_DATA"==e?1:0))break;REDIM(unref(f),[b],"");REDIM(unref(g),[b],"");REDIM(unref(j),[b],0);f.arrAccess(b-1).values[tmpPositionCache]=e;g.arrAccess(b-1).values[tmpPositionCache]=LCASE_Str(INIGET_Str(unref(global12_menu_dir_Str),CAST2STRING(b)+"type","NO_DATA"));
j.arrAccess(b-1).values[tmpPositionCache]=CAST2FLOAT(INIGET_Str(unref(global12_menu_dir_Str),CAST2STRING(b)+"value","NO_DATA"))}if(CAST2FLOAT(0==global9_menu_fade?1:0))if(CAST2FLOAT(0==global12_menu_keymode?1:0)){e=func12_MenuNavigate();if(CAST2FLOAT(e!=static13_MenuShow_last_key_down?1:0))if(a=0,a=e,1==a)global8_menu_pos+=-1;else if(3==a)global8_menu_pos+=1;else if(2==a){if(CAST2FLOAT("root"!=global12_menu_dir_Str?1:0))global9_menu_back=1,global9_menu_fade=-0.1}else if(4<=a&&5>=a)if(a="",a=MID_Str(unref(g.arrAccess(global8_menu_pos).values[tmpPositionCache]),
0,3),"dir"==a)global9_menu_fade=-0.1;else if("but"==a)global9_menu_fade=-0.1;else if("tog"==a){if(c=CAST2FLOAT(SPLITSTR(unref(g.arrAccess(global8_menu_pos).values[tmpPositionCache]),unref(static7_MenuShow_tmp_Str)," ,:",1)-1))j.arrAccess(global8_menu_pos).values[tmpPositionCache]=CAST2FLOAT(MOD(CAST2INT(j.arrAccess(global8_menu_pos).values[tmpPositionCache]+c+1),unref(CAST2INT(c)))),INIPUT(unref(global12_menu_dir_Str),CAST2STRING(global8_menu_pos+1)+"value",unref(CAST2STRING(j.arrAccess(global8_menu_pos).values[tmpPositionCache])))}else"key"==
a&&(global12_menu_keymode=1);else static13_MenuShow_last_key_down=CAST2FLOAT(-1);if(CAST2FLOAT(0<e?1:0))static13_MenuShow_last_key_down=e}else if(CAST2FLOAT(KEY(1)))global12_menu_keymode=0;else if(func15_keydef_getstate(a),e=func19_keydef_get_name_Str(a,global14_menu_nullstate),CAST2FLOAT(""!=e?1:0))INIPUT(unref(global12_menu_dir_Str),CAST2STRING(global8_menu_pos+1)+"value",unref(e)),global12_menu_keymode=CAST2FLOAT(-1);else if(CAST2FLOAT(0>global12_menu_keymode?1:0))global12_menu_keymode=0;global8_menu_pos=
CAST2FLOAT(1<b?1:0)?CAST2FLOAT(MOD(CAST2INT(global8_menu_pos+b-1),CAST2INT(b-1))):0;if(CAST2FLOAT(0<global9_menu_fade?1:0))if(global9_menu_fade+=CAST2INT(CAST2FLOAT(MIN(20,CAST2FLOAT(GETTIMER())))/500),CAST2FLOAT(1<global9_menu_fade?1:0))global9_menu_fade=0;if(CAST2FLOAT(0>global9_menu_fade?1:0))if(global9_menu_fade+=-CAST2INT(CAST2FLOAT(MIN(20,CAST2FLOAT(GETTIMER())))/500),CAST2FLOAT(global9_menu_fade<=CAST2FLOAT(-1)?1:0))if(global9_menu_fade=0,global9_menu_back)global9_menu_back=0,global12_menu_dir_Str=
"root",global9_menu_fade=0.1;else if(a="",a=g.arrAccess(global8_menu_pos).values[tmpPositionCache],"dir"==a){global12_menu_dir_Str=INIGET_Str(unref(global12_menu_dir_Str),CAST2STRING(global8_menu_pos+1)+"value","NO_DATA");if(CAST2FLOAT("NO_DATA"==global12_menu_dir_Str?1:0))global12_menu_dir_Str="root";global9_menu_fade=0.1;global8_menu_pos=0}else if("button"==a)return tryClone(unref(j.arrAccess(global8_menu_pos).values[tmpPositionCache]));DIM(unref(k),[b],"");for(c=1;forCheck(c,b-1,1);c+=1){if(CAST2FLOAT("toggle"==
MID_Str(LCASE_Str(unref(g.arrAccess(c-1).values[tmpPositionCache])),0,6)?1:0))(e=CAST2FLOAT(SPLITSTR(unref(g.arrAccess(c-1).values[tmpPositionCache]),unref(static7_MenuShow_tmp_Str)," ,:",1)-1))&&(k.arrAccess(c-1).values[tmpPositionCache]=static7_MenuShow_tmp_Str.arrAccess(j.arrAccess(c-1).values[tmpPositionCache]+1).values[tmpPositionCache]);if(CAST2FLOAT("key"==LCASE_Str(unref(g.arrAccess(c-1).values[tmpPositionCache]))?1:0))k.arrAccess(c-1).values[tmpPositionCache]=func24_keydef_get_nice_name_Str(INIGET_Str(unref(global12_menu_dir_Str),
CAST2STRING(c)+"value","NO_DATA"))}func8_MenuDraw(global9_menu_fade,global8_menu_pos,f,k);return 0}
function func8_MenuDraw(a,b,c,e){var a=unref(a),b=unref(b),c=unref(c),e=unref(e),f=[0],g=[0],j=0,k=[0],h=[0],m=0,n=0,p=0,r=0,q=0,l=0,s=0,j="";GETSCREENSIZE(f,g);GETFONTSIZE(k,h);m=CAST2FLOAT(BOUNDS(c,0));if(CAST2FLOAT(0==m?1:0))return 0;r=CAST2FLOAT(INTEGER(0.75*f[0]));q=(4+m)*h[0];if(CAST2FLOAT(0<a?1:0))a=1-a;n=a*f[0]+(f[0]-r)/2;p=(g[0]-q)/2;ALPHAMODE(-0.5);DRAWRECT(unref(n),unref(p),unref(r),unref(q),RGB(0,0,0));ALPHAMODE(0);if(global12_menu_keymode)PRINT("REDEFINE: "+c.arrAccess(global8_menu_pos).values[tmpPositionCache],
unref(n),p+h[0],0);else{for(l=0;forCheck(l,m-1,1);l+=1){s=p+2*h[0]+l*h[0];if(CAST2FLOAT(l==b?1:0))ALPHAMODE(-0.7),DRAWRECT(unref(n),unref(s),unref(r),unref(h[0]),RGB(255,255,255)),ALPHAMODE(0);PRINT(unref(c.arrAccess(l).values[tmpPositionCache]),n+k[0],unref(s),0);(j=CAST2FLOAT(LEN(e.arrAccess(l).values[tmpPositionCache])))&&PRINT("["+e.arrAccess(l).values[tmpPositionCache]+"]",n+r-(j+3)*k[0],unref(s),0)}for(l=CAST2FLOAT(-1);forCheck(l,m,1);l+=1)s=p+2*h[0]+l*h[0],PRINT("|",unref(n),unref(s),0),PRINT("|",
n+r-k[0],unref(s),0);m=CAST2FLOAT(INTEGER(r/k[0])-1);for(l=0;forCheck(l,m,1);l+=1){j="-";if(CAST2FLOAT(0==l||l==m?1:0))j="#";PRINT(unref(j),n+l*k[0],unref(p),0);PRINT(unref(j),n+l*k[0],p+q-h[0],0)}}return 0}
function type7_CONTROL(){this.attr10_button_Str=this.attr8_down_Str=this.attr6_up_Str=this.attr8_rght_Str=this.attr7_lft_Str="";this.clone=function(){var a={};a.attr7_lft_Str=tryClone(this.attr7_lft_Str);a.attr8_rght_Str=tryClone(this.attr8_rght_Str);a.attr6_up_Str=tryClone(this.attr6_up_Str);a.attr8_down_Str=tryClone(this.attr8_down_Str);a.attr10_button_Str=tryClone(this.attr10_button_Str);a.clone=this.clone;return a};return this}
function type12_KEYDEF_STATE(){this.attr4_keys=new GLBArray;this.attr4_joys=new GLBArray;this.attr4_keys=DIM(new GLBArray,[256],[0]);this.attr4_joys=DIM(new GLBArray,[4,48],[0]);this.clone=function(){var a={};a.attr4_keys=tryClone(this.attr4_keys);a.attr4_joys=tryClone(this.attr4_joys);a.clone=this.clone;return a};return this}"console"==viewMode&&(window.onload=function(){updateConsole()});
var waitload=0,exec=!1,tmpPositionCache=-1,args=Array(64),consoleOutput,consoleSize=1E4,currentDir,mainCall=!1;function STDOUT(a){consoleOutput==void 0&&(consoleOutput=document.getElementById("console"));if(consoleOutput){LEN(consoleOutput.value);LEN(a);consoleOutput.value=consoleOutput.value+a;consoleOutput.scrollTop=consoleOutput.scrollHeight}else console.log(a)}function STDERR(a){STDOUT("Error: "+a)}function STDCOLOR(){}function DEBUG(a){console.log(a)}
function END(){window.onbeforeunload();throw"endprog";}function GETTIMERALL(){return(new Date).getTime()-startTime}
function PLATFORMINFO_Str(a){switch(a){case "":return"HTML5";case "DOCUMENTS":case "APPDATA":case "TEMP":return"/";case "ID":return""+uniqueId;case "DEVICE":return"DESKTOP";case "BATTERY":return(a=navigator.battery||window.navigator.battery||navigator.battery||navigator.mozBattery||navigator.webkitBattery)?a.level*100:100;case "TIME":var a=new Date,b=function(a){a=CAST2STRING(a);LEN(a)==1&&(a="0"+a);return a};return b(a.getFullYear())+"-"+b(a.getMonth())+"-"+b(a.getDate())+" "+b(a.getHours())+":"+
b(a.getMinutes())+":"+b(a.getSeconds());case "COMPILED":return rot13(compileTime);case "VERSION":return rot13(userDefVersion);case "HOSTID":return rot13(hostId);case "LOCALE":return navigator.language||window.navigator.userLanguage||window.navigator.language;default:return LEN(a)>LEN("GLEXT:")&&MID_Str(a,0,LEN("GLEXT:"))=="GLEXT:"?"0":""}}function GETLASTERROR_Str(){return"0 Successfull"}
function SHELLCMD(a,b,c,e){try{e[0]=CAST2FLOAT(eval(a))}catch(f){e[0]=0;e[0]=0;throwError("SHELLCMD raised ab error.")}}function SHELLEND(a){try{eval(a)}catch(b){throwError("SHELLEND raised an error")}END()}function CALLBYNAME(a){return eval("if (window['"+a+"']) window."+a+"(); else ret = 0;")}var expectedErrors=["endprog","GLBERR"],callStack=[];function StackFrame(a,b){this.name=a;this.info=b}function stackPush(a,b){callStack.push(new StackFrame(a,b))}function stackPop(){callStack.pop()}
function stackTrace(){for(var a="",b=callStack.length-1;b>=0;b--)a=a+("\tin '"+callStack[b].name+"' in file '"+MID_Str(callStack[b].info,INSTR(callStack[b].info,":")+1)+"' in line '"+MID_Str(callStack[b].info,0,INSTR(callStack[b].info,":"))+"'\n");return a}function throwError(a){if(callStack.length>0)throw a;alert(a);END()}
function formatError(a){a=a.message?a.message:a.toString();if(debugMode)var b=__debugInfo,a="Error:\n '"+a+"' "+("\nAppeared in line '"+MID_Str(b,0,INSTR(b,":"))+"' in file '"+MID_Str(b,INSTR(b,":")+1)+"' "),a=a+("\n\n"+stackTrace());return a}function dumpArray(a){for(var b="",c=false,e=0;e<a.length;e++){c&&(b=b+", ");b=b+("'"+a[e]+"'");c=true}return"["+b+"]"}function forCheck(a,b,c){return c>0?a<=b:c<0?a>=b:true}
function isKnownException(a){for(var a=a.toString(),b=0;b<expectedErrors.length;b++)if(a.indexOf(expectedErrors[b])==0)return true;return false}function unref(a){return a instanceof Array?a[0]:a}function ref(a){return a instanceof Array?a:[a]}function tryClone(a){switch(typeof a){case "undefined":case "function":case "string":case "boolean":case "number":break;default:return a instanceof Array?[tryClone(a[0])]:a.clone()}return a}
function updateConsole(){try{if(!mainCall){main();mainCall=true}if(!waitload&&!exec){exec=true;typeof GLB_ON_INIT=="function"&&GLB_ON_INIT()}else window.requestAnimFrame(updateConsole,100)}catch(a){a!="endprog"&&alert(formatError(a))}}var dataLabel,dataPosition;function RESTORE(a){dataLabel=a;dataPosition=0}function READ(){var a=dataLabel[dataPosition];dataPosition++;return a}
function GLBArray(){this.values=[];this.dimensions=[0];this.defval=0;this.arrAccess=function(){tmpPositionCache=0;for(var a=arguments.length-1;a>=0;a--){a>=this.dimensions.length&&throwError("Wrong dimension count '"+(arguments.length-1)+"' expected '"+this.dimensions.length+"'");var b=CAST2INT(arguments[a]);b<0&&(b=this.dimensions[a]+b);(b<0||b>=this.dimensions[a])&&throwError("Array index out of bounds access, position: "+dumpArray(arguments));args[a]=b}switch(arguments.length){case 1:tmpPositionCache=
args[0];break;case 2:tmpPositionCache=args[0]+args[1]*this.dimensions[0];break;case 3:tmpPositionCache=args[0]+args[1]*this.dimensions[0]+args[1]*this.dimensions[0]*this.dimensions[1]+args[2]*this.dimensions[0]*this.dimensions[1]*this.dimensions[2];break;case 4:tmpPositionCache=args[0]+args[1]*this.dimensions[0]+args[1]*this.dimensions[0]*this.dimensions[1]+args[2]*this.dimensions[0]*this.dimensions[1]*this.dimensions[2]+args[2]*this.dimensions[0]*this.dimensions[1]*this.dimensions[2]*this.dimensions[3];
break;default:b=this.values.length/this.dimensions[arguments.length-1];for(a=arguments.length-1;a>=0;a--){tmpPositionCache=tmpPositionCache+args[a]*b;b=b/this.dimensions[a-1]}}return this};this.clone=function(){var a=new GLBArray;a.values=this.values.slice(0);a.dimensions=this.dimensions.slice(0);a.defval=this.defval;a.arrAccess=this.arrAccess;if(this.values!=void 0&&this.values.dimensions!=void 0)for(var b=0;b<this.values.length;b++)a.values[b]=tryClone(this.values[b]);return a};return this}
function realArrSize(a){var b=1;for(d in a){a[d]=CAST2INT(Math.round(a[d]));b=b*a[d]}return b}function DIM(a,b,c){a.values=Array(realArrSize(b));a.dimensions=b;a.defval=c;for(b=0;b<a.values.length;b++)a.values[b]=tryClone(c);return a}function REDIM(a,b,c){var e=a.values.length;a.dimensions=b;a.defval=c;a.values.length=realArrSize(b);for(i=0;i<a.values.length;i++)i>=e&&(a.values[i]=tryClone(a.defval));return a}function BOUNDS(a,b){return a.dimensions[b]}
function DIMPUSH(a,b){REDIM(a,[a.values.length+1],a.defval);a.values[a.values.length-1]=tryClone(b)}function DIMDEL(a,b){a.values.splice(b,1);a.dimensions[0]--}function DIMDATA(a,b){a.values=b;a.dimensions=[b.length]}function LEN(a){if(typeof a=="string"||typeof a=="number")return CAST2STRING(a).length;if(a.constructor===GLBArray)return BOUNDS(a,0);throwError("Cannot get the length of: "+typeof a+", "+a.constructor)}function SEEDRND(a){rand=new RandomNumberGenerator(a)}var rand=null;
function RND(a){if(a==0)return 0;a<0&&(a=-a);rand||(rand=new RandomNumberGenerator(GETTIMERALL()));return(a+1)*rand.next()}function MIN(a,b){return a<b?a:b}function MAX(a,b){return a>b?a:b}function ABS(a){return Math.abs(a)}function SGN(a){return a>0?1:a<0?-1:0}function SIN(a){return Math.sin(deg2rad(a))}function COS(a){return Math.cos(deg2rad(a))}function TAN(a){return Math.tan(deg2rad(a))}function ACOS(a){return Math.acos(deg2rad(a))}function ASIN(a){return Math.asin(deg2rad(a))}
function ASL(a,b){return a<<b}function ASR(a,b){return a>>b}function ATAN(a,b){return rad2deg(Math.atan2(a,b))}function bAND(a,b){return a&b}function bOR(a,b){return a|b}function bXOR(a,b){return a^b}function bNOT(a){return~a}function MOD(a,b){return CAST2INT(a%b)}function FMOD(a,b){return a%b}function FINDPATH(){alert("TODO: findpath")}function LOGN(a){return Math.log(a)}function POW(a,b){return Math.pow(a,b)}function SQR(a){return Math.sqrt(a)}function SWAP(a,b){a[0]=b[0];b[0]=a[0]}
function SORTARRAY(a,b){a.values.sort(b==0?function(a,b){a=unref(a);b=unref(b);switch(typeof o){case "undefined":case "function":case "string":case "boolean":case "number":return a<b?-1:a>b?1:0;default:alert("TODO: Default sortarray with types!")}}:function(a,e){return b([a],[e])})}function deg2rad(a){return a*(Math.PI/180)}function rad2deg(a){return a*(180/Math.PI)}
function CAST2INT(a){if(a instanceof Array)return[CAST2INT(a[0])];switch(typeof a){case "function":return 1;case "undefined":return 0;case "number":a<0?a=Math.ceil(a):a>0&&(a=Math.floor(a))}switch(""+a){case "true":case "false":a=0}a=parseInt(a);isNaN(a)&&(a=0);return a}function INTEGER(a){return CAST2INT(a)}
function CAST2FLOAT(a){if(a instanceof Array)return[CAST2FLOAT(a[0])];switch(typeof a){case "function":return 1;case "undefined":return 0}switch(""+a){case "true":case "false":a=0}a=parseFloat(a);isNaN(a)&&(a=0);return a}function STACKTRACE_Str(){return stackTrace()}function FORMAT_Str(a,b,c){for(var c=CAST2STRING(c),e=INSTR(c,"."),f=REVINSTR(c,"."),g=e;g<a;g++)c=" "+c;for(g=f;g<b;g++)c=c+"0";for(g=a;g<e;g++)c=MID_Str(c,1);for(g=b;g<f;g++)c=MID_Str(c,0,LEN(c)-1);return c}
function ENCRYPT_Str(a,b){var c=0;for(i=0;i<LEN(a);i++)c=c+ASC(a,i);var c=c%16,e="";for(i=0;i<LEN(b);i++)e=e+CHR_Str(ASC(b,i)+c);return e}function DECRYPT_Str(a,b){var c=0;for(i=0;i<LEN(a);i++)c=c+ASC(a,i);var c=c%16,e="";for(i=0;i<LEN(b);i++)e=e+CHR_Str(ASC(b,i)-c);return e}function LCASE_Str(a){return a.toLowerCase()}function UCASE_Str(a){return a.toUpperCase()}
function MID_Str(a,b,c){try{return c==-1?a.substr(b):a.substr(b,c)}catch(e){throwError("string error (MID$): '"+a+"' start: '"+b+"' count: '"+c+"'")}}function LEFT_Str(a,b){try{return a.substr(0,b)}catch(c){throwError("string error (LEFT$): '"+a+"' count: '"+b+"'")}}function RIGHT_Str(a,b){try{return a.substr(LEN(a)-b,b)}catch(c){throwError("string error (RIGHT$): '"+a+"' count: '"+b+"'")}}
function CAST2STRING(a){if(a instanceof Array)return[CAST2STRING(a[0])];switch(typeof a){case "function":return"1";case "undefined":return"0"}return""+a}function INSTR(a,b,c){return c==-1?a.indexOf(b):a.indexOf(b,c)}function REVINSTR(a,b,c){return c==-1?a.lastIndexOf(b):a.lastIndexOf(b,c)}function CHR_Str(a){return String.fromCharCode(a)}function REPLACE_Str(a,b,c){for(var e=0;;){e=a.indexOf(b,e);if(e==-1)break;a=a.substring(0,e)+c+a.substring(e+b.length);e=e+c.length}return a}
function TRIM_Str(a,b){return LTRIM_Str(RTRIM_Str(a,b),b)}function LTRIM_Str(a,b){for(i=0;i<a.length;i++){var c=a.charAt(i);if(b.indexOf(c)==-1)return a.substr(i)}return""}function RTRIM_Str(a,b){for(i=a.length-1;i>=0;i--){var c=a.charAt(i);if(b.indexOf(c)==-1)return a.substr(0,i+1)}return""}function ASC(a,b){try{return a.charCodeAt(b)}catch(c){throwError("string error (ASC): '"+a+"' index: '"+b+"'")}}
function SPLITSTR(a,b,c,e){try{var f=0;REDIM(b,[0],b.defval);for(var g=0;g<=a.length;g++){var j=a.charAt(g);if(c.indexOf(j)!=-1||g==a.length){var k=MID_Str(a,f,g-f);if(k!=""||!e)b.defval instanceof Array?DIMPUSH(b,[k]):DIMPUSH(b,k);f=g+1}}return LEN(c)}catch(h){throwError("string error (SPLITSTR): '"+str+"' split: '"+c+"' dropEmpty: "+e)}}function URLENCODE_Str(a){return encodeURI(a)}function URLDECODE_Str(a){return decodeURI(a)}var channels=[];
function GENFILE(){for(var a=0;a<channels.length;a++)if(!channels[a])return a;return channels.length}
function rawpath(a,b){for(var a=(TRIM_Str(b.getFileSystem().getCurrentDir()," ")+TRIM_Str(a," ")).toLowerCase(),c=0,e=b,f=0;f<a.length;f++)switch(a.charAt(f)){case "/":if(f>0){c=a.substr(c,f-c);e=e.getSubDir(c);c=f+1}else c=1;break;case ".":var g=function(){f++;return f<a.length};if(!g())break;if(a.charAt(f)=="."){e=e.getParent();if(!g())break;a.charAt(f)!="/"&&throwError("Expecting '/'");c=f+1}else a.charAt(f)=="/"&&(c=f+1)}return new FilePointer(a.substr(c,a.length-c),e)}
function FilePointer(a,b){this.name=a;this.dir=b}
function VirtualFileSystem(a){this.mainDir=new VirtualDirectory("",null,this);this.curDir="";this.copyFile=function(a,c){if(this.doesFileExist(form)){var e=this.getFile(a).data;this.createFile(c,e)}};this.getCurrentDir=function(){return this.curDir};this.setCurrentDir=function(a){LEFT_Str(a,1)!="/"&&(a=a+"/");this.curDir=a};this.getFile=function(a){a=rawpath(a,this.mainDir);return a.dir.getFile(a.name)};this.getDir=function(a){return rawpath(a,this.mainDir).dir};this.doesFileExist=function(a){try{var c=
rawpath(a,this.mainDir);return c.dir.doesFileExist(c.name)}catch(e){}return false};this.doesDirExist=function(){try{var a=rawpath(file,this.mainDir);return a.dir.doesDirExist(a.name)}catch(c){}return false};this.removeFile=function(a){a=rawpath(a,this.mainDir);a.dir.removeFile(a.name)};this.removeDir=function(a){a=rawpath(a,this.mainDir);a.dir.removePath(a.name)};this.createFile=function(a,c){if(this.doesFileExist(a)){var e=this.getFile(a);e.data=c;return e}e=rawpath(a,this.mainDir);return e.dir.createFile(e.name,
c)};this.cD=this.createDir=function(a){if(this.doesDirExist(a))return this.getDir(a);a=rawpath(a,this.mainDir);return a.dir.createDir(a.name)};this.cF=this.createFile;this.getMainDir=function(){return this.mainDir};this.save=function(){return this.mainDir.save()};if(a!=void 0){window.fileSystem=this;eval(REPLACE_Str(a,"t.","window.fileSystem."))}}
function VirtualDirectory(a,b,c){this.name=a;this.parent=b;this.subDirs=[];this.files=[];this.fileSystem=c;this.getList=function(){return this.subDirs.concat(this.files)};this.getFileSystem=function(){return this.fileSystem};this.doesDirExist=function(){for(var a=0;a<this.subDirs.length;a++)if(this.subDirs[a].name==file)return true;return false};this.doesFileExist=function(a){for(var b=0;b<this.files.length;b++)if(this.files[b].name==a)return true;return false};this.removeFile=function(a){for(var b=
0;b<this.files.length;b++)if(this.files[b].name==a){this.files.splice(b,1);return}throwError("FileNotFound "+a)};this.removeDir=function(a){for(var b=0;b<this.subDirs.length;b++)if(this.subDirs[b].name==a){this.subDirs.splice(b,1);return}throwError("DirNotFound "+a)};this.createDir=function(a){a=new VirtualDirectory(a,this,this.fileSystem);this.subDirs.push(a);return a};this.createFile=function(a,b){var c=new VirtualFile(this,a,b);this.files.push(c);return c};this.getFile=function(a){for(var b=0;b<
this.files.length;b++)if(this.files[b].name==a)return this.files[b];throwError("file not found")};this.getDir=function(a){for(var b=0;b<this.subDirs.length;b++)if(this.subDirs[b].name==a)return this.subDirs[b];throwError("Dir not found")};this.getSubDir=function(a){for(var b=0;b<this.subDirs.length;b++)if(this.subDirs[b].name==a)return this.subDirs[b];throwError("Dir not found: "+a)};this.getParent=function(){return this.parent};this.getPath=function(){return(this.getParent()?this.getParent().getPath()+
"/":"")+this.name};this.save=function(){var a="";this.getParent()!=null&&(a='t.cD("'+this.getPath()+'");\n');for(var b=0;b<this.files.length;b++)a=a+this.files[b].save();for(b=0;b<this.subDirs.length;b++)a=a+this.subDirs[b].save();return a}}function VirtualFile(a,b,c){this.name=b;this.data=c;this.dir=a;this.getName=function(){return this.name};this.getData=function(){return this.data};this.save=function(){return't.cF("'+this.dir.getPath()+"/"+this.name+'", '+JSON.stringify(this.data)+");\n"}}
function Channel(a,b,c){this.channel=a;this.mode=c;this.ptr=0;if(fileSystem.doesFileExist(b))this.file=fileSystem.getFile(b);else if(staticFileSystem.doesFileExist(b))if(c==1)this.file=staticFileSystem.getFile(b);else{a=staticFileSystem.getFile(b);this.file=fileSystem.createFile(b,a.data)}else if(c!=1)try{this.file=fileSystem.createFile(b,[])}catch(e){throwError("cannot create file: "+b)}else throwError("file not found: "+b);if(c==-1)this.ptr=this.file.data.length;this.updateSize=function(){if(this.ptr>
this.file.data.length)this.file.data.length=this.ptr};this.checkPosition=function(){this.ptr>this.file.data.length&&throwError("Reached end of file: '"+this.ptr+"' filesize: '"+this.file.data.length+"'")};this.ENDOFFILE=function(){return this.ptr>this.file.data.length||this.ptr<0};this.FILESEEK=function(a,b){var c=this.ptr;switch(b){case -1:this.ptr=this.file.data.length-a;break;case 0:this.ptr=a;break;case 1:this.ptr=this.ptr+a}if(this.ENDOFFILE())this.ptr=c};this.READLINE=function(){for(var a="",
b="";(b=String.fromCharCode(this.file.data[this.ptr]))!="\n"&&this.ptr<this.file.data.length;){a=a+b;this.ptr++}this.ptr++;a.substr(a.length-1,1)=="\r"&&(a=a.substr(0,a.length-1));this.checkPosition();return a};this.READBYTE=function(){this.ptr++;var a=new Int8Array(1);a[0]=this.file.data[this.ptr-1];this.checkPosition();return a[0]};this.READUBYTE=function(){this.ptr++;var a=new Uint8Array(1);a[0]=this.file.data[this.ptr-1];this.checkPosition();return a[0]};this.READWORD=function(){this.ptr=this.ptr+
2;var a=new ArrayBuffer(2),b=new Uint8Array(a);b[0]=this.file.data[this.ptr-2];b[1]=this.file.data[this.ptr-1];a=new Int16Array(a);this.checkPosition();return a[0]};this.READUWORD=function(){this.ptr=this.ptr+2;var a=new ArrayBuffer(2),b=new Uint8Array(a);b[0]=this.file.data[this.ptr-2];b[1]=this.file.data[this.ptr-1];a=new Uint16Array(a);this.checkPosition();return a[0]};this.READLONG=function(){this.ptr=this.ptr+4;var a=new ArrayBuffer(4),b=new Uint8Array(a);b[0]=this.file.data[this.ptr-4];b[1]=
this.file.data[this.ptr-3];b[2]=this.file.data[this.ptr-2];b[3]=this.file.data[this.ptr-1];a=new Int32Array(a);this.checkPosition();return a[0]};this.READULONG=function(){this.ptr=this.ptr+4;var a=new ArrayBuffer(4),b=new Uint8Array(a);b[0]=this.file.data[this.ptr-4];b[1]=this.file.data[this.ptr-3];b[2]=this.file.data[this.ptr-2];b[3]=this.file.data[this.ptr-1];a=new Uint32Array(a);this.checkPosition();return a[0]};this.READIEEE=function(){this.ptr=this.ptr+8;var a=new ArrayBuffer(8),b=new Uint8Array(a);
b[0]=this.file.data[this.ptr-8];b[1]=this.file.data[this.ptr-7];b[2]=this.file.data[this.ptr-6];b[3]=this.file.data[this.ptr-5];b[4]=this.file.data[this.ptr-4];b[5]=this.file.data[this.ptr-3];b[6]=this.file.data[this.ptr-2];b[7]=this.file.data[this.ptr-1];a=new Float64Array(a);this.checkPosition();return a[0]};this.READSHORTIEEE=function(){this.ptr=this.ptr+4;var a=new ArrayBuffer(4),b=new Uint8Array(a);b[0]=this.file.data[this.ptr-4];b[1]=this.file.data[this.ptr-3];b[2]=this.file.data[this.ptr-2];
b[3]=this.file.data[this.ptr-1];a=new Float32Array(a);this.checkPosition();return a[0]};this.READSTR=function(a){for(var b="",c=0;c<a;c++)b=b+CHR_Str(this.READUBYTE());return b};this.WRITEBYTE=function(a){var b=new Int8Array(1);b[0]=a;this.file.data[this.ptr]=b[0];this.ptr++;this.updateSize()};this.WRITEUBYTE=function(a){var b=new Uint8Array(1);b[0]=a;this.file.data[this.ptr]=b[0];this.ptr++;this.updateSize()};this.WRITEWORD=function(a){var b=new ArrayBuffer(2);(new Int16Array(b))[0]=a;a=new Uint8Array(b);
for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITEUWORD=function(a){var b=new ArrayBuffer(2);(new Uint16Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITELONG=function(a){var b=new ArrayBuffer(4);(new Int32Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITEULONG=function(a){var b=new ArrayBuffer(4);(new Uint32Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);
this.updateSize()};this.WRITEIEEE=function(a){var b=new ArrayBuffer(8);(new Float64Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITESHORTIEEE=function(a){var b=new ArrayBuffer(4);(new Float32Array(b))[0]=a;a=new Uint8Array(b);for(b=0;b<a.length;b++)this.WRITEUBYTE(a[b]);this.updateSize()};this.WRITESTR=function(a){for(var b=0;b<a.length;b++)this.WRITEUBYTE(ASC(a,b));this.updateSize()};this.WRITELINE=function(a){this.WRITESTR(a+"\r\n")}}
function OPENFILE(a,b,c){try{channels[a]=new Channel(a,b,c);if(a>=channels.length)channels.length=a+1;return 1}catch(e){return 0}}function getChannel(a){channels[a]||throwError("Cannot find channel: "+a);return channels[a]}function ENDOFFILE(a){return getChannel(a).ENDOFFILE()?1:0}function FILEPOSITION(a){return getChannel(a).ptr}function FILESEEK(a,b,c){getChannel(a).FILESEEK(b,c)}
function KILLFILE(a){try{fileSystem.doesDirExist(a)?fileSystem.removeDir(a):fileSystem.doesFileExist(a)&&fileSystem.removeFile(a)}catch(b){}try{staticFileSystem.doesDirExist(a)?staticFileSystem.removeDir(a):staticFileSystem.doesFileExist(a)&&staticFileSystem.removeFile(a)}catch(c){}}function CLOSEFILE(a){channels[a]=null;saveFileSystem()}function READUBYTE(a,b){b[0]=getChannel(a).READUBYTE()}function READBYTE(a,b){b[0]=getChannel(a).READBYTE()}
function READWORD(a,b){b[0]=getChannel(a).READWORD()}function READUWORD(a,b){b[0]=getChannel(a).READUWORD()}function READLONG(a,b){b[0]=getChannel(a).READLONG()}function READULONG(a,b){b[0]=getChannel(a).READULONG()}function READSHORTIEEE(a,b){b[0]=getChannel(a).READSHORTIEEE()}function READIEEE(a,b){b[0]=getChannel(a).READIEEE()}function READLINE(a,b){b[0]=getChannel(a).READLINE()}function READSTR(a,b,c){b[0]=getChannel(a).READSTR(c)}function WRITEUBYTE(a,b){getChannel(a).WRITEUBYTE(b)}
function WRITEBYTE(a,b){getChannel(a).WRITEBYTE(b)}function WRITEWORD(a,b){getChannel(a).WRITEWORD(b)}function WRITEUWORD(a,b){getChannel(a).WRITEUWORD(b)}function WRITELONG(a,b){getChannel(a).WRITELONG(b)}function WRITEULONG(a,b){getChannel(a).WRITEULONG(b)}function WRITESHORTIEEE(a,b){getChannel(a).WRITESHORTIEEE(b)}function WRITEIEEE(a,b){getChannel(a).WRITEIEEE(b)}function WRITELINE(a,b){getChannel(a).WRITELINE(b)}function WRITESTR(a,b){getChannel(a).WRITESTR(b)}function SETSHOEBOX(){}
function GETCOMMANDLINE_Str(){var a=window.location.href,b=INSTR(a,"?");return b==-1?"":REPLACE_Str(MID_Str(a,b+1),"&"," ")}function GETCURRENTDIR_Str(){return fileSystem.getCurrentDir()}function SETCURRENTDIR(a){var a=rawpath(fileSystem.getCurrentDir()+a,fileSystem.getMainDir()).dir.getPath()+a,b=false,c=false;try{fileSystem.setCurrentDir(a);b=true}catch(e){}try{staticFileSystem.setCurrentDir(a);c=true}catch(f){}return b&&c?1:0}
function DOESFILEEXIST(a){return fileSystem.doesFileExist(a)||staticFileSystem.doesFileExist(a)?1:0}function DOESDIREXIST(a){return fileSystem.doesDirExist(a)||staticFileSystem.doesDirExist(a)?1:0}function GETFILESIZE(a){try{var b=null;fileSystem.doesFileExist(a)?b=fileSystem.getFile(a):staticFileSystem.doesFileExist(a)?b=staticFileSystem.getFile(a):throwError("Cannot find file: "+a);if(b)return b.data.length}catch(c){}return 0}
function GETFILELIST(a,b){try{REDIM(b,[0],b.defval);var c=fileSystem.getDir("").getList().concat(staticFileSystem.getDir("").getList()),e=0,f=0,g=[];g.push(".");g.push("..");for(var j=0;j<c.length;j++){var k=c[j],h;a:{for(var m=k.name,n=0,p=0,p=0;p<=a.length;p++){var r=a.charAt(p);switch(r){case "*":p++;var q=a.charAt(p);for(p--;m.charAt(n)!=q||n>m.length;)n++;break;case "?":n++;break;default:if(r!=m.charAt(n)){h=false;break a}n++}}h=true}if(h){k instanceof VirtualDirectory?e++:k instanceof VirtualFile?
f++:throwError("Unknown file type");g.push(k.name)}}for(j=0;j<g.length;j++)b.defval instanceof Array?DIMPUSH(b,[g[j]]):DIMPUSH(b,g[j]);return e*4096+f}catch(l){throwError("GETFILELIST error: find: '"+a+"'")}}function COPYFILE(a,b){fileSystem.copyFile(a,b);staticFileSystem.copyFile(a,b)}function CREATEDIR(a){try{fileSystem.createDir(a);staticFileSystem.createDir(a);return 1}catch(b){}return 0}function PUTENV(a,b){localStorage.setItem(("env_"+a).toLowerCase(),b)}
function GETENV_Str(a){return localStorage.getItem(("env_"+a).toLowerCase())}function rot13(a){var b="";for(i=0;i<LEN(a);i++)b=b+CHR_Str(ASC(a,i)-13);return b}function SLEEP(a){for(var b=GETTIMERALL();GETTIMERALL()-b<a;);}
function INI(a){this.parse=function(a){try{for(var b=a.replace("\r").split("\n"),c="",e=0;e<b.length;e++){var h=b[e];INSTR(h,";")!=-1&&(h=MID_Str(h,0,INSTR_Str(h,";")));if(MID_Str(h,0,1)=="[")c=MID_Str(h,1,REVINSTR(h,"]")-1);else if(INSTR(h,"=")!=-1){var m=MID_Str(h,0,INSTR(h,"=")),n=MID_Str(h,INSTR(h,"=")+1);INIPUT(c,m,n)}}}catch(p){throwError("INI parse error: '"+a*NaN)}};this.put=function(a,b,c){try{for(var a=a.toLowerCase(),e,h=0;h<this.cats.length;h++)if(this.cats[h].name==a){e=this.cats[h];
if(b==""&&c==""){this.cats.splice(h,1);return}break}if(!e){e=new INICat(a);this.cats.push(e)}e.put(b,c)}catch(m){throwError("INIPUT error cat: '"+a+"' key: '"+b+"' value: '"+c+"'")}};this.get=function(a,b){try{for(var a=a.toLowerCase(),c,e=0;e<this.cats.length;e++)if(this.cats[e].name==a){c=this.cats[e];break}c||(c=new INICat(a));return c.get(b)}catch(h){throwError("INIGET error cat: '"+a+"' key: '"+b+"'")}};this.save=function(){for(var a="",b=0;b<this.cats.length;b++){a=a+("["+this.cats[b].name+
"]\n");a=a+this.cats[b].save()}return a};this.cats=[];this.channel=2674;try{OPENFILE(this.channel,a,0);var b=GETFILESIZE(a);if(b>0){var c=[""];READSTR(this.channel,c,b);b=curIni;curIni=this;this.parse(c[0]);curIni=b}}catch(e){throwError("INI load error: '"+a+"'")}}
function INICat(a){this.name=a;this.keys=[];this.put=function(a,c){for(var a=a.toLowerCase(),e,f=0;f<this.keys.length;f++)if(this.keys[f].key==a){e=this.keys[f];if(c==""){this.keys.splice(f,1);return}break}if(!e){e=new INIKeyValue(a,c);this.keys.push(e)}};this.get=function(a){for(var a=a.toLowerCase(),c,e=0;e<this.keys.length;e++)if(this.keys[e].key==a){c=this.keys[e];break}if(!c){c=new INIKeyValue(a,"");this.keys.push(c)}return c.value};this.save=function(){for(var a="",c=0;c<this.keys.length;c++)a=
a+(this.keys[c].key+"="+this.keys[c].value+"\n");return a}}function INIKeyValue(a,b){this.key=a;this.value=b}var curIni=null;function INIOPEN(a){if(curIni){var b=curIni.save();WRITESTR(curIni.channel,b);CLOSEFILE(curIni.channel)}curIni=a==""?null:new INI(a)}function INIPUT(a,b,c){curIni&&curIni.put(a,b,c)}function INIGET_Str(a,b){if(curIni)return curIni.get(a,b)}
function nextRandomNumber(){var a=this.A*(this.seed%this.Q)-this.R*(this.seed/this.Q);this.seed=a>0?a:a+this.M;return this.seed*this.oneOverM}function RandomNumberGenerator(a){this.seed=a;this.A=48271;this.M=2147483647;this.Q=this.M/this.A;this.R=this.M%this.A;this.oneOverM=1/this.M;this.next=nextRandomNumber;return this}
window.localStorage||Object.defineProperty(window,"localStorage",new function(){var a=[],b={};Object.defineProperty(b,"getItem",{value:function(a){return a?this[a]:null},writable:false,configurable:false,enumerable:false});Object.defineProperty(b,"key",{value:function(b){return a[b]},writable:false,configurable:false,enumerable:false});Object.defineProperty(b,"setItem",{value:function(a,b){if(a)document.cookie=escape(a)+"="+escape(b)+"; path=/"},writable:false,configurable:false,enumerable:false});
Object.defineProperty(b,"length",{get:function(){return a.length},configurable:false,enumerable:false});Object.defineProperty(b,"removeItem",{value:function(a){if(a){var b=new Date;b.setDate(b.getDate()-1);document.cookie=escape(a)+"=; expires="+b.toGMTString()+"; path=/"}},writable:false,configurable:false,enumerable:false});this.get=function(){var c,e;for(e in b){c=a.indexOf(e);c===-1?b.setItem(e,b[e]):a.splice(c,1);delete b[e]}for(;a.length>0;a.splice(0,1))b.removeItem(a[0]);for(var f=0,g=document.cookie.split(/\s*;\s*/);f<
g.length;f++){c=g[f].split(/\s*=\s*/);if(c.length>1){b[e=unescape(c[0])]=unescape(c[1]);a.push(e)}}return b};this.configurable=false;this.enumerable=true});function NETWEBEND(a){window.location=a;END()}window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
function checkBrowserName(a){return navigator.userAgent.toLowerCase().indexOf(a.toLowerCase())>-1?true:false}window.onbeforeunload=function(){CALLBYNAME("GLB_ON_QUIT");saveFileSystem()};function saveFileSystem(){localStorage.setItem("filesystem",fileSystem.save())}var tmpAlert=alert;alert=function(a){tmpAlert(a)};"graphics"==viewMode&&(window.onload=function(){init2D("GLBCANVAS")});
var sprites=[],screens=[],waitload=0,curScreen=null,context=null,canvas=null,mouseX=0,mouseY=0,clrColor=RGB(0,0,0),keyInput=[],fontbuffer=null,backbuffer=null,initCalled=!1,lastShwscrn=0,showFPS=-1,framePrev=0,frameDelay=0,canvasWidth,canvasHeight,anyKeyPress=!1,anyMousePress=!1,background=null,loopFunc=null,loops=[],usedSoundformat="ogg",hibernate=!1,mouseLeft=!1,mouseRight=!1,mouseMiddle=!1,mouseSpeedX=0,mouseSpeedY=0,lastMouseX,lastMouseY,transCol=null,setBmp=null;
function update2D(){try{if(initCalled){if(setBmp){setBmp();setBmp=null}mouseSpeedX=mouseX-lastMouseX;mouseSpeedY=mouseY-lastMouseY;if(hibernate){if(ANYMOUSE()||ANYKEY()||mouseSpeedX||mouseSpeedY)hibernate=false}else{canvasWidth=canvas.width;canvasHeight=canvas.height;if(showFPS==-1)waitload?GLB_ON_LOADING&&GLB_ON_LOADING():loopFunc();else{var a=GETTIMERALL(),b=a-framePrev;if(b>=frameDelay){waitload?GLB_ON_LOADING&&GLB_ON_LOADING():loopFunc();frameDelay=showFPS;b>frameDelay&&(frameDelay=frameDelay-
(b-frameDelay));framePrev=a}}}anyMousePress=anyKeyPress=false;lastMouseX=mouseX;lastMouseY=mouseY}else{initCalled=true;main()}window.requestAnimFrame(update2D,frontbuffer.canvas)}catch(c){c!="endprog"&&alert(formatError(c))}}function domExceptionError(a){if(a instanceof DOMException)a.code==18?throwError("Cannot access to ressource (maybe pixel data?). If you use Chrome, please run in localhost or use another browser!"):throwError("Unknown DOM error :(");else throw a;}
function PUSHLOOP(a){var b=eval("window['"+a+"']");if(b==void 0){loopFunc=function(){throwError("Call to undefined loop!")};throwError("Cannot push undefined loop: '"+a+"'")}loopFunc=b;loops.push([b,a])}function POPLOOP(){loops.pop();loops.length==0&&throwError("Cannot pop loop, because loop stack is empty!");loopFunc=loops[loops.length-1][0]}function GETCURRENTLOOP_Str(){return loops[loops.length-1][1]}
function RETURNTOLOOP(a){for(eval("window."+a)==void 0&&throwError("Cannot return to undefined loop: '"+a+"'");GETCURRENTLOOP_Str()!=a;)POPLOOP()}function X_MAKE2D(){}function SHOWSCREEN(){lastShwscrn=GETTIMERALL();if(initCalled){USESCREEN(-2);CLEARSCREEN(clrColor);USESCREEN(-1);frontbuffer.context.drawImage(backbuffer.canvas,0,0);CLEARSCREEN(clrColor);background&&backbuffer.context.drawImage(background,0,0)}}
function init2D(a){function b(a){if(a.stopPropagation){a.stopPropagation();a.preventDefault()}else{a.cancelBubble=true;a.returnValue=false}}var c=document.createElement("audio"),e=false,f=false;if(c.canPlayType){e=!!c.canPlayType&&""!=c.canPlayType("audio/mpeg");e=e=="maybe"||e=="probably"||e==true?true:false;f=!!c.canPlayType&&""!=c.canPlayType('audio/ogg; codecs="vorbis"');f=f=="maybe"||f=="probably"||f==true?true:false}!f&&!e&&throwError("Your browser is not able to play sound... please use a newer browser.");
usedSoundFormat=f?"ogg":"mp3";frontbuffer=new Screen(document.getElementById(a),-2);register(frontbuffer);a=document.createElement("canvas");a.width=frontbuffer.canvas.width;a.height=frontbuffer.canvas.height;backbuffer=new Screen(a,-1);register(backbuffer);typeof GLB_ON_LOADING=="undefined"&&(GLB_ON_LOADING=null);USESCREEN(-2);if(!context){throwError("Canvas unsupported, please use a newer browser.");END()}canvas.style.cursor="none";canvas.onmousemove=function(a){a||(a=window.event());mouseX=a.clientX-
canvas.offsetLeft;mouseY=a.clientY-canvas.offsetTop};canvas.onmousedown=function(a){a||(a=window.event());anyMousePress=true;switch(a.button){case 0:mouseLeft=true;break;case 1:mouseMiddle=true;break;case 2:mouseRight=true}b(a)};canvas.onmouseup=function(a){a||(a=window.event());switch(a.button){case 0:mouseLeft=false;break;case 1:mouseMiddle=false;break;case 2:mouseRight=false}b(a)};canvas.onmouseout=function(a){mouseMiddle=mouseRight=mouseLeft=false;b(a)};document.onkeydown=function(a){a||(a=window.event());
anyKeyPress=keyInput[a.keyCode]=true};document.onkeyup=function(a){a||(a=window.event());keyInput[a.keyCode]=false};USESCREEN(-1);CLEARSCREEN(RGB(0,0,0));SHOWSCREEN();try{window.GLB_ON_LOOP?PUSHLOOP("GLB_ON_LOOP"):PUSHLOOP("GLB_MAIN_LOOP")}catch(g){}update2D()}function deInit2D(){context=canvas=null;sprites=[];screens=[];waitload=0;curScreen=null;clrColor=RGB(0,0,0);keyInput=[];backbuffer=fontbuffer=null;initCalled=false}
function register(a){if(a instanceof Sprite){sprites[a.num]=a;if(a.num>=sprites.length)sprites.length=a.num+1}else if(a instanceof Screen){screens[a.num]=a;if(a.num>=screens.length)screens.length=a.num+1}else if(a instanceof Sound){sounds[a.num]=a;if(a.num>=sounds.length)sounds.length=a.num+1}else if(a instanceof SoundChannel){soundChannels[a.num]=a;if(a.num>=soundChannels.length)soundChannels.length=a.num+1}else throwError("Cannot register unknown object: "+a.constructor);return a.num}
function Sprite(a,b){this.img=a;this.num=b;this.data=null;this.loaded=false}function getSprite(a){if(sprites[a]){sprites[a].loaded||throwError("Image not yet loaded '"+a+"'");return sprites[a]}throwError("Image not available '"+a+"'")}
function Screen(a,b,c){this.canvas=a;this.context=a.getContext("2d");this.realwidth=this.canvas.width;this.realheight=this.canvas.height;this.realx=this.canvas.offsetLeft;this.realy=this.canvas.offsetRight;this.num=b+2;this.spr=c;this.context==null&&throwError("Given buffer does not support '2d'")}function FOCEFEEDBACK(a,b){var c=navigator.vibrate||navigator.mozVibrate;c&&c(b)}function GETTIMER(){return GETTIMERALL()-lastShwscrn}
function ALPHAMODE(a){if(a<0){context.globalCompositeOperation="lighter";a=1-a-1}else if(a>0)context.globalCompositeOperation="lighter";else{context.globalCompositeOperation="source-over";a=1}canvas.globalAlpha=a}function SETPIXEL(a,b,c){DRAWRECT(a,b,1,1,c)}function LIMITFPS(a){showFPS=a}function RGB(a,b,c){a==void 0&&(a=0);b==void 0&&(b=0);c==void 0&&(c=0);return a%256*65536+b%256*256+c%256}function SETTRANSPARENCY(a){transCol=a}function SMOOTHSHADING(){throwError("TODO: SMOOTHSHADING")}
function SETSCREEN(a,b){canvas.width=a;canvas.height=b}function VIEWPORT(a,b,c,e){if(a!=0||b!=0||c!=canvas.width||e!=canvas.height){context.beginPath();context.rect(a,b,c,e);context.clip();context.closePath()}}function ALLOWESCAPE(){throwError("TODO: allowescape")}function AUTOPAUSE(){throwError("TODO: autopause")}function HIBERNATE(){hibernate=true}function GETSCREENSIZE(a,b){a[0]=canvas.width;b[0]=canvas.height}
function GETSPRITESIZE(a,b,c){b[0]=0;c[0]=0;if(sprites[a]&&sprites[a].loaded){b[0]=sprites[a].img.width;c[0]=sprites[a].img.height}}function GETDESKTOPSIZE(a,b){a[0]=window.innerWidth;b[0]=window.innerHeight}function GETFONTSIZE(a,b){var c=context.measureText("W");c||throwError("Font metrics unsupported!");a[0]=c.width;b[0]=c.height?c.height:16}function ISFULLSCREEN(){throwError("TODO: isfullscreen")}
function GETPIXEL(a,b){var c=a*4+b*canvas.width*4;throwError("TODO: getpixel");return RGB(c,c+1,c+2)}function CREATESCREEN(a,b,c,e){var f=document.createElement("canvas");f.width=c;f.height=e;register(new Screen(f,a,b));register(new Sprite(f,b))}function USESCREEN(a){var b=curScreen;if(b&&b.spr)getSprite(b.spr).data=null;if(curScreen=screens[a+2]){context=curScreen.context;canvas=curScreen.canvas}else curScreen=b}function BLENDSCREEN(){throwError("TODO: blendscreen")}
function CLEARSCREEN(a){context.save();context.fillStyle=formatColor(a);context.fillRect(0,0,canvas.width,canvas.height);clrColor=a;context.restore()}function BLACKSCREEN(){CLEARSCREEN(RGB(0,0,0))}function USEASBMP(){background=backbuffer.canvas;var a=document.createElement("canvas");a.width=canvasWidth;a.height=canvasHeight;backbuffer=new Screen(a,-1);register(backbuffer);USESCREEN(-1)}
function LOADBMP(a){var b=new Image;if(DOESFILEEXIST(a))throwError("TODO: load image from virtual file system");else{b.onload=function(){background=b};b.onerror=function(){throwError("BMP '"+a+"' not found!")};b.src=fileSystem.getCurrentDir()+a}}function SAVEBMP(){throwError("TODO: savebmp")}function SAVESPRITE(){throwError("TODO: savesprite")}
function DRAWLINE(a,b,c,e,f){context.save();context.strokeStyle=formatColor(f);context.beginPath();context.moveTo(CAST2INT(a),CAST2INT(b));context.lineTo(CAST2INT(c),CAST2INT(e));context.stroke();context.restore()}function DRAWRECT(a,b,c,e,f){context.save();context.fillStyle=formatColor(f);context.fillRect(CAST2INT(a),CAST2INT(b),CAST2INT(c),CAST2INT(e));context.restore()}function formatColor(a){for(a=a.toString(16);a.length<6;)a="00"+a;return"#"+a}function ENDPOLY(){throwError("TODO: endpoly")}
function POLYVECTOR(){throwError("TODO: polyvector")}function STARTPOLY(){throwError("TODO: startpoly")}function GENSPRITE(){for(var a=0;a<sprites.length;a++)if(!sprites[a])return a;return sprites.length}function DRAWANIM(){throwError("TODO: drawanim")}function DRAWSPRITE(a,b,c){a=getSprite(a);context.drawImage(a.img,CAST2INT(b),CAST2INT(c))}function ROTOSPRITE(a,b,c,e){if(e%360==0)DRAWSPRITE(a,b,c);else{context.save();context.setRotation(e*Math.PI/180);DRAWSPRITE(a,b,c);context.restore()}}
function ZOOMSPRITE(a,b,c,e,f){if(e==1&&f==1)DRAWSPRITE(a,b,c);else if(e!=0&&f!=0){context.save();context.scale(e,f);DRAWSPRITE(a,b,c);context.restore()}}function STRETCHSPRITE(a,b,c,e,f){a=getSprite(a);e!=0&&f!=0&&context.drawImage(a.img,CAST2INT(b),CAST2INT(c),CAST2INT(e),CAST2INT(f))}function ROTOZOOMSPRITE(a,b,c,e,f){context.save();context.scale(f,f);ROTOSPRITE(a,b,c,e);context.restore()}function ROTOZOOMANIM(){throwError("TODO: rotozoomanim")}
function ROTOANIM(){throwError("TODO: rotoanim")}function ZOOMANIM(){throwError("TODO: zoomanim")}function STRETCHANIM(){throwError("TODO: stretchanim")}function GRABSPRITE(a,b,c,e,f){(e<1||f<1)&&throwError("Invalid width/height!");try{var g=context.getImageData(b,c,e,f),j=document.createElement("canvas");j.width=e;j.height=f;j.getContext("2d").putImageData(g,0,0);var k=new Sprite(j,a);k.loaded=true;register(k)}catch(h){domExceptionError(h)}}
function PRINT(a,b,c){context.save();context.font="12pt Consolas";context.fillStyle="#ffffff";context.fillText(a,CAST2INT(b),CAST2INT(c)+12);context.restore()}function SETFONT(){throwError("TODO: setfont")}function MOUSEAXIS(a){switch(a){case 0:return mouseSpeedX;case 1:return mouseSpeedY;case 2:return 0;case 3:return mouseLeft?1:0;case 4:return mouseRight?1:0;case 5:return mouseMiddle?1:0}}function MOUSESTATE(a,b,c,e){a[0]=mouseX;b[0]=mouseY;c[0]=mouseLeft?1:0;e[0]=mouseRight?1:0}
function SYSTEMPOINTER(a){canvas.style.cursor=a?"auto":"none"}function KEY(a){a=glb2jsKeyCode(a);return keyInput[a]?1:0}
function glb2jsKeyCode(a){switch(a){case 14:return 8;case 15:return 9;case 28:return 13;case 42:return 16;case 29:case 157:return 17;case 56:case 29:case 184:return 18;case 197:return 19;case 58:return 20;case 1:return 27;case 201:return 33;case 57:return 32;case 209:return 34;case 207:return 35;case 178:return 36;case 203:return 37;case 200:return 38;case 205:return 39;case 208:return 40;case 183:return 44;case 210:return 45;case 211:return 46;case 11:return 48;case 2:return 49;case 3:return 50;
case 4:return 51;case 5:return 52;case 6:return 53;case 7:return 54;case 8:return 55;case 9:return 56;case 10:return 57;case 30:return 65;case 48:return 66;case 46:return 67;case 32:return 68;case 18:return 69;case 33:return 70;case 34:return 71;case 35:return 72;case 23:return 73;case 36:return 74;case 37:return 75;case 38:return 76;case 50:return 77;case 49:return 78;case 24:return 79;case 25:return 80;case 16:return 81;case 19:return 82;case 31:return 83;case 20:return 84;case 22:return 85;case 47:return 86;
case 17:return 87;case 45:return 88;case 44:return 89;case 21:return 90;case 219:return 91;case 220:return 92;case 82:return 96;case 79:return 97;case 80:return 98;case 81:return 99;case 75:return 100;case 76:return 101;case 77:return 102;case 71:return 103;case 72:return 104;case 73:return 105;case 55:return 106;case 78:return 107;case 74:return 109;case 83:return 110;case 181:return 111;case 59:return 112;case 60:return 113;case 61:return 114;case 62:return 115;case 63:return 116;case 64:return 117;
case 65:return 118;case 66:return 119;case 67:return 120;case 68:return 121;case 87:return 122;case 88:return 123;case 69:return 144;case KEY_SCROLLLOCK=145:return 70}}function INKEY_Str(){return""}function ANYKEY(){return anyKeyPress?1:0}function ANYMOUSE(){return anyMousePress?1:0}
function SPRCOLL(a,b,c,e,f,g){var a=getSprite(a),e=getSprite(e),j=function(a){try{var b=document.createElement("canvas");b.width=a.img.width;b.height=a.img.height;var c=b.getContext("2d");c.drawImage(a.img,0,0);a.data=c.getImageData(0,0,b.width,b.height)}catch(e){domExceptionError(e)}};a.data==null&&j(a);e.data==null&&j(e);return isPixelCollision(a.data,b,c,e.data,f,g)?1:0}function ANIMCOLL(){throwError("TODO: animcoll")}
function isPixelCollision(a,b,c,e,f,g){var b=Math.round(b),c=Math.round(c),f=Math.round(f),g=Math.round(g),j=a.width,k=a.height,h=e.width,m=e.height,n=Math.max(b,f),p=Math.max(c,g),r=Math.min(b+j,f+h),k=Math.min(c+k,g+m);if(n>=r||p>=k)return false;var m=r-n,q=k-p,a=a.data,e=e.data;if(m<4&&q<4)for(q=n;q<r;q++)for(var l=p;l<k;l++){if(a[(q-b+(l-c)*j)*4+3]!==0&&e[(q-f+(l-g)*h)*4+3]!==0)return true}else for(var m=m/3,s=q/3,m=~~m===m?m:m+1|0,s=~~s===s?s:s+1|0,t=0;t<s;t++)for(var u=0;u<m;u++)for(l=p+t;l<
k;l=l+s)for(q=n+u;q<r;q=q+m)if(a[(q-b+(l-c)*j)*4+3]!==0&&e[(q-f+(l-g)*h)*4+3]!==0)return true;return false}function BOXCOLL(a,b,c,e,f,g,j,k){return a<=f+j&&b<=g+k&&a+c>=f&&b+e>=g?1:0}
function LOADSPRITE(a,b){var c=new Image,e=new Sprite(c,b);if(DOESFILEEXIST(a))throwError("TODO: load image from virtual file system");else{c.onerror=function(){if(sprites[b]){waitload--;sprites[b]=null;a!=""&&a!="0"&&throwError("Image '"+b+"' '"+a+"' not found!")}};c.onload=function(){if(!e.loaded){waitload--;e.loaded=true;try{if(transCol){var a=c.width,b=c.height,j=document.createElement("canvas");j.width=a;j.height=b;var k=new Screen(j,-42);k.context.drawImage(c,0,0);for(var h=k.context.getImageData(0,
0,a,b),m=0;m<b;m++){outpos=inpos=m*a*4;for(var n=0;n<a;n++){var p=h.data[inpos++],r=h.data[inpos++],q=h.data[inpos++],l=h.data[inpos++];RGB(p,r,q)==transCol&&(l=0);h.data[outpos++]=p;h.data[outpos++]=r;h.data[outpos++]=q;h.data[outpos++]=l}}k.context.putImageData(h,0,0);e.img=j}}catch(s){domExceptionError(s)}}};c.src=fileSystem.getCurrentDir()+a}register(e);waitload++}function LOADANIM(){throwError("TODO: LOADANIM")}function LOADFONT(){throwError("TODO: loadfont")}
function MEM2SPRITE(){throwError("TODO: mem2sprite")}function SPRITE2MEM(){throwError("TODO: sprite2mem")}function LOADSPRITEMEM(){throwError("TODO: loadspritemem")}function LOOPMOVIE(){throwError("TODO: loopmovie")}function PLAYMOVIE(){throwError("TODO:playmovie")}var sounds=[],soundChannels=[];function genSoundChannel(){for(var a=1;a<soundChannels.length;a++)if(!soundChannels[a])return a;return soundChannels.length+1}
function Sound(a,b,c){this.num=b;this.file=a;this.loaded=false;this.buffers=[];this.buffers.length=c;this.sound=new Audio(a);this.sound.load();waitload++;var e=this;this.sound.addEventListener("onerror",function(){waitload--;a!=""&&a!="0"&&throwError("Sound '"+b+"' '"+a+"' not found!")},false);this.sound.addEventListener("canplaythrough",function(){if(!e.loaded){waitload--;for(var a=0;a<e.buffers.length;a++)e.buffers[a]=new SoundChannel(this)}e.loaded=true},false)}
function SoundChannel(a){this.sound=a.cloneNode(true);this.sound.load();this.num=genSoundChannel();this.playing=this.loaded=false;this.playTime=0;this.play=function(){this.playing&&this.stop();this.sound.currentTime=0;this.playing=true;this.playTime=GETTIMERALL();this.sound.play()};this.stop=function(){this.sound.pause();this.sound.currentTime=0;this.playing=false;this.playTime=0};var b=this;this.sound.addEventListener("canplaythrough",function(){b.loaded||waitload--;b.loaded=true},false);this.sound.addEventListener("ended",
function(){b.stop()},false);waitload++}function LOADSOUND(a,b,c){var e=REPLACE_Str(MID_Str(a,MAX(0,a.lastIndexOf("/")),-1),"/",""),a=REPLACE_Str(a,e,".html5_convertedsounds_"+e)+"/",a=new Sound("./"+(usedSoundFormat=="ogg"?a+"sound.ogg":a+"sound.mp3"),b,c);register(a);return a}
function PLAYSOUND(a){if(a=sounds[a]){for(var b=null,c=GETTIMERALL()+1,e=0;e<a.buffers.length&&c!=0;e++)if(a.buffers[e].playTime<c){c=a.buffers[e].playTime;b=a.buffers[e]}b?b.play():throwError("No channel available...");return b.num}return 0}function HUSH(){for(var a=0;a<soundChannels.length;a++)soundChannels[a]&&soundChannels[a].playing&&soundChannels[a].stop()}function SOUNDPLAYING(a){return soundChannels[a]&&soundChannels[a].playing?0:1}function PLAYMUSIC(){}
function STOPMUSIC(){SOUNDPLAYING(0)&&soundChannels[0].stop()}function ISMUSICPLAYING(){return SOUNDPLAYING(0)}var static7_MenuShow_tmp_Str=new GLBArray,static13_MenuShow_last_key_down=CAST2FLOAT(-1);initFS&&initFS();
